### ISSUE TITLE
Replacing Dockerfile convenience directives

### ISSUE THREAD

**Issue by chouseknecht** [ansible/ansible-container#10]
There are directives in the Dockerfile syntax that provide needed shortcuts for doing things like creating environment vars, setting the working directory, etc. These are examples I've thought of or run into thus far:

- env
- workdir
- entrypoint

These are really documentation issues and not a deficiency in ansible-container. For example, both *env* and *entrypoint* can be specified in the compose used to instantiate the services/containers at run time. So we might not have a way (I don't think) to bake these settings into the image, but we can certainly inject them at run time.

The workaround for *workdir* is most likely to just include the starting directory in the command to be executed. And that perhaps brings up another point- the command won't be baked into the image, but specified at run time.

**Comment by j00bar** [comment]
I'm not sure what this issue is reporting, or if it's still relevant. Please update?
