### ISSUE TITLE
Ansible role not copying files correctly

### ISSUE THREAD

**Issue by mdevlin1** [ansible/ansible-container#102]
I have been setting up ansible-container to provision some docker containers. I am trying to provision these containers with a few roles I have defined. In the roles I copy files from a directory above the actual task, this is an example: 
`copy:
src: ../files/elastic-repo
dest: /etc/yum.repos.d/elasticsearch.repo`

This does not seem to work properly. I am getting this error:
`ansible-container_1  | fatal: [mgt]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to find '../files/elastic-repo' in expected paths."}
ansible-container_1  | 
`

I have already tested this in a virtual machine so I know the syntax is correct.

**Comment by j00bar** [comment]
This is a known issue reported upstream to Ansible.

https://github.com/ansible/ansible/pull/16173
