### ISSUE TITLE
lookup() no longer works with ansible-container

### ISSUE THREAD

**Issue by kelf** [ansible/ansible-container#105]
lookup() no longer works with ansible-container.

It appears to search the remote container rather then the local box.

**Comment by gregdek** [comment]
"No longer works" with ansible-container? Does that mean it worked at some point and then failed to work?

**Comment by kelf** [comment]
To clarify, lookup works on the calling environment, so files outside the playbook file tree can be referenced.  Since this project executes the playbook inside a container, files not found inside the playbook directory structure will fail a lookup.

This is probably not easily solved, so a word of caution around it might be nice.

**Comment by j00bar** [comment]
This is the expected behavior, as `ansible-container` runs in its own container environment. The entire project, including the `ansible` directory are mounted into the build container, and so `lookup()` will work properly relative to that mount, as seen in our example project.
