### ISSUE TITLE
Base image, building, environment vars, and image layer caching?

### ISSUE THREAD

**Issue by darkn3rd** [ansible/ansible-container#107]
The example only shows downloading images then adding stuff on top of the image.  Is it possible to just build an image from `container.yaml`, then use `main.yaml` for building of an fresh blank image?  Can we use equivalent of `FROM` in `main.yaml`?  

There are many scenarios to do this, especially if a base line container is built by Ops for security, and an application specific image is built inheriting a secure Ops base container.  

Also, when building, each task has their own image layer?  So this way we don't have to rebuild a package manifest (e.g. `requirements.txt`, `Gemfile`, `package.json`, `bower.json`, etc.) each and every time there is a rebuild.

Can we configure vars in container environment that can inherited from the host environment?  Use environment variables from the shell in the `main.yaml` and `container.yaml`?

**Comment by gregdek** [comment]
Might be helpful to make this multiple issues, since there are multiple topics/requests in here. :)

One point of clarity: yes, each task that runs at build time creates a separate layer, because that's how docker exec works.

**Comment by darkn3rd** [comment]
One idea, maybe radical, how about having an abstraction above the playbook `main.yml`, a sort of meta-playbook, where there can be layers.  Each layer generates a playbook that creates a combined image that is orchestrated by `container.yml` later.

Another idea, is use the Dockerfile in the background, then have the layering support, where each task is an image, but is provisioned by the sidekick Ansible container.

**Comment by j00bar** [comment]
To @gregdek 's response, not quite - each task does not add an additional layer - each `build` run creates an additional layer.

The vars seems to have been reported separately as #120.

You may specify any base image you want in the `container.yml` file - be it one in the engine already or in a container registry to download. This is our equivalent of the `FROM` directive.

I'm opening a separate issue for layer caching, as this is a topic under active discussion among our team.

As that covers everything, I'm closing this issue. Thanks!
