### ISSUE TITLE
Error: image library/example-django not found

### ISSUE THREAD

**Issue by GPegel** [ansible/ansible-container#112]
I've followed the installation instructions and everything went well. Also building the example image went ok but when I want to run the example containter as described in the README.md I receive this error message. 

`$ sudo ansible-container run`

`No DOCKER_HOST environment variable found. Assuming UNIX socket at /var/run/docker.sock
The PWD variable is not set. Defaulting to a blank string.
Attaching to ansible_ansible-container_1
Cleaning up Ansible Container builder...
The PWD variable is not set. Defaulting to a blank string.
Pulling repository docker.io/library/example-django
Error: image library/example-django not found
`

I'm very new into this and I'm asking myself, am I doing something wrong or is the image not available any more?

**Comment by j00bar** [comment]
Couple of questions:

* Why are you using `sudo`?
* Can you please provide the output of:
  * `docker images`
  * `docker ps -a`

**Comment by GPegel** [comment]
- I used `sudo` because without, I got more error messages. I solved this by doing a chown at the docker user directory so now I'm able to execute docker commands without using `sudo`
- Output of docker images:

![image](https://cloud.githubusercontent.com/assets/10278496/16610482/c6c27110-435b-11e6-811d-b8118cf48b04.png)

- Output of docker ps -a

![image](https://cloud.githubusercontent.com/assets/10278496/16610594/81b99804-435c-11e6-87a7-d4801bd8a4e7.png)

**Comment by gregdek** [comment]
So there's a Django container there, but it's called ansible_django_1 -- not sure why it's trying to invoke library/example-django instead...

**Comment by mablae** [comment]
Did you try to referece to the base image without the `library/` prefix in container.yml?

**Comment by j00bar** [comment]
The command `ansible-container run` will launch docker-compose specifying `image: example-django`, which would be the repository name for the image built by `ansible-container build`. Docker's default behavior is, when it doesn't find that locally, to assume you're pulling an image from Docker Hub, and absent a namespace prefix (e.g. the `ansible/` in `ansible/ansible-container`) it assumes it's the Docker, Inc., blessed image (prefix `library/`).

What I see from your `docker ps -a` is that your build failed. Your gulp and django containers existed with a non-zero status code. Can you please post the build output? Thanks!

**Comment by gregdek** [comment]
Closing. @GPegel if you continue to have this issue, feel free to reopen and provide build output.
