### ISSUE TITLE
Passing ansible_options as build arguments not formatted correctly

### ISSUE THREAD

**Issue by podnov** [ansible/ansible-container#118]
I'm trying to pass --extra-vars to ansible through the ansible-container build command like so:

```
ansible-container --debug build -- --extra-vars "'smtap_ws_facts_file=smtap_ws-prod.json smtap_silo_qos_etl_version=1.5.4'"
```

The ansible-playbook commands being generated by ansible-container end up looking like this:

```
/usr/local/bin/ansible-playbook -i /etc/ansible/inventory/hosts -c docker ['--extra-vars', "'smtap_ws_facts_file=smtap_ws-prod.json smtap_silo_qos_etl_version=1.5.4'"] --list-hosts main.yml

/usr/local/bin/ansible-playbook -vvv -i /etc/ansible/inventory/hosts -c docker ['--extra-vars', "'smtap_ws_facts_file=smtap_ws-prod.json smtap_silo_qos_etl_version=1.5.4'"] main.yml
```

I modified the existing jinja templates like so to get it to work: #117

Full command line output is available [here](https://github.com/ansible/ansible-container/files/354980/ansible-container-argument-array-failure.txt)

**Comment by gregdek** [comment]
Closed by #117
