### ISSUE TITLE
Support for Variables in Container.yml

### ISSUE THREAD

**Issue by darkn3rd** [ansible/ansible-container#120]
### DESCRIPTION

Docker-Compose has support to source in environment variables from the current running environment.  It can also default them in a `./.env`.  I would also like the source them as well, or specify them in the file.  It would be nice to have shared variables both in `container.yml` and `main.yml`.

Example:

```yaml
version: '1'
vars:
  web_port: 8080
  app_root: "/usr/src/app"
services:
  express:
    image: node:argon
    command: [ "npm", "start" ]
    working_dir: "{{ app_root }}"
    environment:
       EXPRESS_PORT: "{{ web_port }}"
    ports:
      - "{{ web_port }}:{{ web_port }}"
registries: {}
```

**Comment by dmsimard** [comment]
Yeah... :+1: this would be nice.

**Comment by chouseknecht** [comment]
While working on moving Galaxy to containers and Galaxy deployment to using Ansible Container, I ran into this as well. We can fix the lack of .env support by adjusting the base_path value we pass into project_from_options() [here](https://github.com/ansible/ansible-container/blob/develop/container/docker/engine.py#L335). If we passed in 'self.base_path/ansible' it would automatically pick up '.env'. However, it would change the value of ${PWD} in container.yml. 

Changing the value of ${PWD} will break existing container.yml files, if they container the env_file directive like so:

```
services:
   foo:
      env_file:
         - ${PWD}/ansible/galaxy/environment.var
```

Any strong objections to making this change?

As to the use of .env... IMHO, using .env is awful. I don't want variables in a hidden file. Things should be obvious and self documenting. Using a hidden file make things not obvious and not self documenting. I would like to have a vars file much the same as ansible-playbook has *--extra-vars* and have the ability to pass in a vars file to template container.yml as described above. We'll have to document order of precedence, but overall should not be too difficult. I think adding this feature gives yet another advantage over using Dockerfile and straight-up Docker compose. Am I wrong in thinking this way?

**Comment by dmsimard** [comment]
Vars should just be pulled from Ansible ? group_vars, host_vars, defined in inventory or role defaults and so on.

**Comment by chouseknecht** [comment]
I don't think we want to repeat what Ansible already does or duplicate Ansible's code. Nor do we want to blend ansible-playbook with ansible-container. They are separate things and should remain separate.

My point was that we should be able to pass in a *basic* yaml variable file to the build command. Maybe something like... `ansible-container build --vars-file vars.yml`. And vars.yml might contain...

```
---
exposed_ports:
  - '8000:8000'
config_path: "/path/to/config'
```

This would offer the following benefits:

- It's not hidden
- The variables can be used anywhere in container.yml
- Variables not limited to string type.
- Multiple files can be kept in the ansible directory over just a single .env file.
- By applying jinja2 templating to containery.yml we get access to all of jinja2, not just variable substitution.

The question is... what are the downsides? Maybe one downside is potential confusion between an ansible-container vars file vs. an ansible-playbook vars file. Vars files in ansible-playbook can include jina2 and Ansible filters (for example the lookup filter) and references to inventory variables, etc. The vars file for ansible-container would be very basic in comparison.

**Comment by j00bar** [comment]
Proposal:

Interpret `container.yml` values using Jinja expressions as you suggest, and processed outside of the builder container. The variables are resolved with an order of precedence:

1. From the OS environment variables, anything beginning with `AC_` is interpreted as a string variable value, except minus the `AC_` and lower-cased.
2. From a command-line specified path to a YAML or JSON file, whose top level object must be a key-value map.
3. From a new, optional top-level section of the `container.yml` file called `defaults` which can contain dimensional data. The values in this section are not interpreted using Jinja expressions.

Thus the project can be pushed to VCS with defaults in its `container.yml`, a user can maintain a standard and reusable set of overrides in one or more text files, and any given execution can override individual values without need for a text file. And this is fully backward compatible.

**Comment by chouseknecht** [comment]
@j00bar I like it! I'll work on this today and submit a PR for review. This will make the Galaxy implementation much nicer!

**Comment by chouseknecht** [comment]
This is mostly done. I'd like to put together an example or two at ansible-container-examples. Plus, it needs to be documented.

**Comment by chouseknecht** [comment]
I think we can mark this done. There is an example at [ansible-container-examples](https://github.com/ansible/ansible-container-examples/tree/master/elk-stack), and there's some useful documentation [here](http://docs.ansible.com/ansible-container/container_yml/template.html).

**Comment by HackerMD** [comment]
Parsing variables from a file via `--var-file` to  `container.yml` works, but I cannot parse them to playbooks in `main.yml` using the [documented approach](http://docs.ansible.com/ansible-container/container_yml/template.html#variable-files) with jinja templating:

```
ansible-container --project <full-path-to-project> --var-file <full-path-to-var-file> --debug build --roles <full-path-to-roles> -- -e"@<full-path-to-var-file>"
```

gives me

```
ansible-container_1      | ERROR! the file_name '<full-path-to-var-file>' does not exist, or is not readable
```

The same file passed via `--var-file` is found, however.

I also tried using the path relative to the project directory - without success.

**Comment by HackerMD** [comment]
It works when the variable file is called `vars.yml` and located in the project folder.

My use case is the following: I have a playbook directory with `roles` and `group_vars` subdirectories, which I typically use for `ansible-playbook` and would now like to reuse for `ansible-container build`. So I would like to use roles in the `roles` folder (which is possible via `--roles` ), but also include variables defined in files in the `group_vars` folder. How can I achieve this without having to copy or link files or having to define variables separately for building containers?

**Comment by chouseknecht** [comment]
@HackerMD because `ansible-playbook` runs inside the build container, you have to make the roles and var files available inside the container. The most likely way to get it to work without copying things into the `ansible` directory is to use the `--roles-path` and `--with-volumes` options on `ansible-container build`. These allow you to mount paths into the build container. Then you can pass options to `ansible-playbook` using the `--` option, or modify config settings in the project's `ansible/ansible.cfg` file.

**Comment by HackerMD** [comment]
@chouseknecht thank you for pointing out `--with-volumes` option. I got it to work with:

```
ansible-container --project <full-path-to-project> build --roles-path <full-path-to-roles> --with-volumes <full-path-to-playbooks>/group_vars:/local-group-vars
```

and then adding the variables in `main.yaml` using `vars_files:

```
- hosts: all
   vars_files:
     - /local-group-vars/all.yml
   roles: []
```

When running in `--debug` mode` I saw that `--project` path get's mounted at `/ansible-container` and `--roles-path` at `/local-roles`. Wouldn't it be nice to extend this logic to `--var-file`, i.e. automatically make parsed files available at `/local-vars`, for example? In fact, I would find it most intuitive to be able to specify something like `--playbooks-path`, which would point to the top level directory with a layout as recommended in [best practices](http://docs.ansible.com/ansible/playbooks_best_practices.html#directory-layout) and would automatically make `roles` and `group_vars` available to `ansible-playbook` inside the container at `/ansible-container`.

**Comment by HackerMD** [comment]
In addition, variables defined in files provided via `--var-file` are not expanded, e.g.

```yaml
var_1: foo
var_2: {{ var_1 }}/bar
```
won't work.

**Comment by Chrislevi** [comment]
Is there any support for vars defined in inventory hosts? or group_vars provided from playbook dir/inventory dir..

eventually what i'm looking for is compatibility to my already existing ansible code (uncontainerized), and im heavily depending on inventory hosts vars and group_vars with several var precedence logics. and of course jinja2 templating for conf files which i dont see any support for it.
