### ISSUE TITLE
Ansible container doesn't read `ansible.cfg` ?

### ISSUE THREAD

**Issue by brucellino** [ansible/ansible-container#126]
Hi, I have my roles in a non-standard directory and am calling them in my container playbook  - see https://github.com/AAROC/DevOps/blob/master/Ansible/Containers/FutureGatewayAPI/ansible/main.yml

The `ansible-container build` command fails because it can't find the role by name : 

```
ansible-container_1  | ERROR! the role 'fgapiserver-role' was not found in /ansible-container/ansible/roles:/ansible-container/ansible:/
ansible-container_1  | 
ansible-container_1  | The error appears to have been in '/ansible-container/ansible/main.yml': line 9, column 7, but may
ansible-container_1  | be elsewhere in the file depending on the exact syntax problem.
ansible-container_1  | 
ansible-container_1  | The offending line appears to be:
ansible-container_1  | 
ansible-container_1  |   roles:
ansible-container_1  |     - fgapiserver-role
ansible-container_1  |       ^ here
ansible-container_1  | 
ansible_ansible-container_1 exited with code 1
```

I have added an `ansible.cfg` in the directory where I'm running `ansible-container` from , as well as where the playbook is executed from - but the role is not found.

What gives ?

**Comment by chouseknecht** [comment]
What gives is... roles have to be included in the project. They have to be available inside the build container. The playbook run within the container will look for roles in ansible/roles, so if you install them there prior to running `ansible-container build`, it will work.

**Comment by brucellino** [comment]
thanks @chouseknecht for the clarification. What you mentioned did fix my issue, so I'm closing it. 

However....

we have a huge collection of roles developed which are not atomically in Galaxy. I want to have access to this in the ansible-container playbooks, so I tried just adding a symlink to the directory containing the roles in the `ansible/` directory of the ansible-container project. This didn't work, and my only guess is because docker doesn't add symlinked volumes like I naively expected. 

So, at this point my only options are to 

  1. move all our roles to Galaxy and install them on a container-by-container basis (making a huge replication of files)
  1. hack ansible-container to provide a hook in the dockerfile template where it can read a variable to ADD the `roles_path` as specified in the `ansible.cfg` file.

I wanted to do the second option, but if this breaks the design of ansible container, I guess I'll have to figure out something else.

thanks again for the clarification.

**Comment by chouseknecht** [comment]
I think what we need is a way to mount the role_path to the build container. Then you could reference the roles without need to copy or sym link.  So in general... we should provide a mechanism for the user to tweak some things about the build container, like mounting additional volumes. Seems like it should live in container.yml maybe as a special service.

Re-opening as an enhancement.

**Comment by j00bar** [comment]
I'd prefer that we have a command-line option on the `build` command for `--use-etc-ansible`. In the case it's specified, the compose file generated for the `build` step would include a volume directive mounting `/etc/ansible` into the build container, read only, at the same location.

**Comment by chouseknecht** [comment]
Further discussion yielded the following:

- Add build command option *--with-volumes=/path/to/mount:/counter/mount[:permissions]* to allow mounting 0+ arbitrary host volumes to the build container. Multiple volumes will be comma separated. Permissions will match the docker options: ro, rw, z, Z. This would allow, for example, mounting a custom roles path as described above. 

- Add build command option *--use-etc-ansible*, which would be a shortcut for *--with-volumes=/etc/ansible/host:/etc/ansible/host:ro*, making the host /etc/ansible directory available to the build container.

- Document that we no longer drop an ansible.cfg file into the temp directory during the build, which means the user can place a custom ansible.cfg file into the ansible dirctory, and it will be used during the build. Need to test this as well. But, using a custom ansible.cfg and *--with-volumes* to mount a custom path, would provide all the necessary dials needed to mount and use a custom roles path.

**Comment by chouseknecht** [comment]
Turns out argparse handles arrays quite nicely.  You can separate multiple volumes by a single space, as in the following example:

```
ansible-container build --with-volumes /foo:/foo:ro /projects/data/:/data:rw
```

Or, you can do this:

```
ansible-container build --with-volumes /foo:/foo:ro /projects/data/:/data:rw --with-volumes /foo/bar:/bar
 ```

No need for commas.

**Comment by drgeb** [comment]
I am obseriving ansible-container: error: unrecognized arguments: --with-volumes
Not sure what I am doing in correctly

**Comment by nonotest** [comment]
@drgeb I am not sure if the new options have been pushed out to pip yet? seems to still be 0.1

**Comment by drgeb** [comment]
Any idea when this will be implemented or is there a work around anyone can  point me to ?

**Comment by chouseknecht** [comment]
It's in the develop branch. We have not set a date yet for the next official release.

**Comment by drgeb** [comment]
Ok. I let me know if I can help with testing it. do I just do the following: 1. git clone https://github.com/ansible/ansible-container.git -b develop  2. cd ansible-container 3. virtualenv ansible-container 4. source ansible-container/bin/activate 5. pip install ansible-container  6. at this point I can go to my project and run ansible-container using the new --with-volumes arguments

I am totally new to this so just making sure I have the right steps! Let me know when I can test it!! Thanks Chouseknecht!!

**Comment by j00bar** [comment]
All would work except step 5, which should be `python setup.py develop`.

**Comment by drgeb** [comment]
Just tried this with the command:
ansible-container \
    --debug \
    build \
     --with-volumes $PWD/files/ssh/ansible_vault:/root/.ssh/ansible_vault \
     --with-volumes $PWD/files/ssh/id_rsa:/root/.ssh/id_rsa \
     --with-volumes $PWD/files/ssh/id_rsa.pub:/root/.ssh/id_rsa.pub \
     --with-volumes /Users/drgeb/.ansible/roles:/ansible/playbooks/roles \
     --with-volumes $PWD:/ansible/playbooks

and got the error:
ConfigurationError: Volume /Users/drgeb/Programming/git/DockerizedAnsibleOracleRetail/oracle12c.new/files/ssh/ansible_vault:/root/.ssh/ansible_vault- /Users/drgeb/Programming/git/DockerizedAnsibleOracleRetail/oracle12c.new/files/ssh/id_rsa:/root/.ssh/id_rsa- /Users/drgeb/Programming/git/DockerizedAnsibleOracleRetail/oracle12c.new/files/ssh/id_rsa.pub:/root/.ssh/id_rsa.pub- /Users/drgeb/.ansible/roles:/ansible/playbooks/roles- /Users/drgeb/Programming/git/DockerizedAnsibleOracleRetail/oracle12c.new:/ansible/playbooks has incorrect format, should be external:internal[:mode]

Not sure if its what I am doing wrong

**Comment by drgeb** [comment]
It seems its not working when I have multiple volumes specified. Using just one volume is ok. If I also uses spaces it gives me the same error

**Comment by drgeb** [comment]
I tried to look into the code and traced it down to a newline issue.
It seems like ./container/templates/build-docker-compose.j2.yml is missing a new line such that the list of volumes is properly created for the internal docker-compose file used.
I modied the line

    {% if with_volumes %}{% for vol in with_volumes %} - {{ vol }}{% endfor %}{% endif %}

to become the following at then it started to work:

    {% if with_volumes %}{% for vol in with_volumes %}
    - {{ vol }}{% endfor %}{% endif %}

**Comment by chouseknecht** [comment]
That looks like the culprit. I'll test and get the change in today as well as update integration tests. The integration tests only check a single volume. 

Thanks for tracking this down @drgeb. Nice work!

**Comment by j00bar** [comment]
+1 excellent sleuthing
