### ISSUE TITLE
Request for version of setuptools required for ansible-container to install

### ISSUE THREAD

**Issue by sqavenky** [ansible/ansible-container#137]
Issue Type: Documentation Report
Clarification required on the version of setuptools required for installing ansible-container.

It is already reported as an issue and documented as part of installation documentation.
Error: File "setup.py", line 11, in <module>
packages=find_packages(include='container.*'),
TypeError: find_packages() got an unexpected keyword argument 'include'

Based on the documentation i did an upgrade on setuptools using command suggested in documentation "pip install --upgrade setuptools".
This command downloaded setuptools-25.1.0-py.py3-none-any.whl and the installation finished with success with message setuptools 1.1.6 has been successfully installed.

Even after the upgrade the command "python setup.py install" on ansible-container directory (github source download) gives the same error.

OS / ENVIRONMENT
OS:Mac OSX
Python version: 2.7.10

Is there any other way to install ansible-container ?
Or how to overcome this issue?

**Comment by sqavenky** [comment]
I had to uninstall python and reinstall python, pip and setuptools using brew and pip. Then the issue got resolved.

**Comment by pszabop** [comment]
It's November and I'm having this issue.  Perhaps the installation mechanism should be more robust.  I've had no issue with other ansible modules.
