### ISSUE TITLE
sorry, i re-open : Missing privilege separation directory: /var/run/sshd

### ISSUE THREAD

**Issue by MaxiReglisse** [ansible/ansible-container#145]
i added the directory creation, as you suggested: 
    - name: Removes link
      file: path=/var/run state=absent
    - name: Creates directory
      file: path=/var/run state=directory force=yes
but if fails with the same error:
Missing privilege separation directory: /var/run/sshd

**Comment by chouseknecht** [comment]
@MaxiReglisse Here is how to run sshd in a container using Ansible Container. Hope it helps. Apologies for taking so long to get to this.

https://github.com/ansible/ansible-container-examples/tree/master/sshd

**Comment by MaxiReglisse** [comment]
Many thanks for that, it works perfectly !
