### ISSUE TITLE
ansible-container *does not* require docker-engine to be on TCP

### ISSUE THREAD

**Issue by dmsimard** [ansible/ansible-container#149]
I was looking at the documentation and came across a mention that [TCP is required](https://github.com/ansible/ansible-container/blob/df2fecd8d2fc66c1aeca4c352a3becc200086b80/docs/rst/installation.rst#enabling-tcp-for-docker-engine)..

I'm running ansible-container just fine through the UNIX socket - to run docker as an unprivileged user, you need to create a docker group and then add the current user to the group. It's in the [official documentation](https://docs.docker.com/engine/installation/linux/centos/#/create-a-docker-group).

When I run ansible-container with the docker group and the user added to the group, this is what the output looks like:

    No DOCKER_HOST environment variable found. Assuming UNIX socket at /var/run/docker.sock
    Starting Docker Compose engine to build your images...
    Attaching to ansible_ansible-container_1
    Cleaning up Ansible Container builder...
    Attaching to ansible_httpd_1, ansible_ansible-container_1
    ansible-container_1  |
    ansible-container_1  | PLAY [all] *********************************************************************
    [...]

**Comment by chouseknecht** [comment]
Fixed by PR #155.
