### ISSUE TITLE
README's installation hints are outdated

### ISSUE THREAD

**Issue by tomsun** [ansible/ansible-container#195]
##### ISSUE TYPE
 - Documentation Report

##### SUMMARY
README.md currently states `For now, Ansible Container can only be installed from source. See INSTALL.md for details.`

INSTALL.md on the other hand, no longer explains how to install from source (as of df2fecd8d2fc66c1aeca4c352a3becc200086b80) and refers to Pip.

**Comment by chouseknecht** [comment]
Fix included in PR #196
