### ISSUE TITLE
Lacking Documentation for use of Vault (and vars in general)

### ISSUE THREAD

**Issue by AndydeCleyre** [ansible/ansible-container#199]
##### ISSUE TYPE
 - Documentation Report

##### SUMMARY
There is no documentation regarding use of ansible-vault (or vars in the general case) with ansible-container.

**Comment by chouseknecht** [comment]
I know. I know. :-) 

Working on it. Stay tuned, and thank-you for the reminder.

**Comment by chouseknecht** [comment]
Doc site updated. See the [container.yml Jina Templating doc](http://docs.ansible.com/ansible-container/container_yml/template.html). There's also an example over at [ansible-container-examples](https://github.com/ansible/ansible-container-examples/tree/master/elk-stack). Feel free to re-open, if you have more questions or need some help.
