### ISSUE TITLE
Default to /var/run/docker.sock?

### ISSUE THREAD

**Issue by containscafeine** [ansible/ansible-container#206]
##### ISSUE TYPE
 - User Experience?

Hi,

Right now, if `DOCKER_HOST` environment variable is not set, we get `No DOCKER_HOST environment variable found. Assuming UNIX socket at /var/run/docker.sock` logged to the screen.

Since most of the people trying out the project will be using the local socket to connect instead of a TCP one, is it fair to assume that it's a UNIX socket by default, and if not, check for `DOCKER_HOST` variable?

**Comment by j00bar** [comment]
If a user has `DOCKER_HOST` set, we use it. Explicit is better than implicit. This is the same order of precedence as the Docker Engine uses. Thanks!

**Comment by containscafeine** [comment]
Well, makes sense, but how about logging this as a debug, instead of info?
But anyway, just a personal preference, I can stop thinking about it :)
