### ISSUE TITLE
Dockerfile for ansible/ansible-container-builder image 

### ISSUE THREAD

**Issue by drgeb** [ansible/ansible-container#208]
##### ISSUE TYPE # 

 - Documentation Report
- Question:
I need the latest version of ansible inside the container currently you have ansible version 2.1.0.0 and I need 2.1.1.0 since there is a specific bug that has been solved in this issue that I can not get around. 
Where can I find the Dockerfile to build this with the latest ?

Thanks

**Comment by chouseknecht** [comment]
The Dockerfile lives in container/templates/ansible-dockerfile.j2. You could modify your local copy. Then do the following: 
```
# Remove existing ansible-container-builder image
$ docker rmi --force ansible-container-builder 

# Build your project using --local-build. This prevents downloading the Docker Hub image.
$ ansible-container build --local-build 
```

In the meantime, I'm upgrading the ansible/ansible-container-builder:0.2 image found on Docker Hub and testing.

**Comment by chouseknecht** [comment]
The ansible/ansible-builder-container:0.2 image on Docker Hub now containers ansible 2.1.1.0. Tests are passing, so fingers crossed that upgrading Ansible did not break anything. 

You will need to run the latest Ansible Container code from the develop branch in order to use the new image.

**Comment by drgeb** [comment]
I chouseknecht I was busy all week and did not have time to work on this!
When I check I still see version 2.1.0.0  not 2.1.1.0

Will try to do the manual build step next that you proposed!

Below is my output from terminal!.

 drgeb@TheBeast  ~/Programming/git/ansible-container   develop ± docker ps
CONTAINER ID        IMAGE                                   COMMAND                  CREATED             STATUS              PORTS                        NAMES
1747ba046e72        drgeb/mq                                "mq.sh"                  12 seconds ago      Up 9 seconds        22/tcp, 1414/tcp             storemq
860c3d365020        drgeb/oracle-linux                      "/usr/bin/dumb-init -"   12 seconds ago      Up 9 seconds        22/tcp                       ansible_database_1
755c288f1f34        ansible/ansible-container-builder:0.2   "/usr/local/bin/build"   12 seconds ago      Up 9 seconds                                     ansible_ansible-container_1
e6b7783a46d1        drgeb/oracle-linux                      "/usr/bin/dumb-init -"   12 seconds ago      Up 9 seconds        22/tcp, 0.0.0.0:80->80/tcp   ansible_storeserver_1
 drgeb@TheBeast  ~/Programming/git/ansible-container   develop ± docker exec -ti ansible_ansible-container_1 /bin/sh
# ansible --version
ansible 2.1.0.0
  config file = /ansible-container/ansible/ansible.cfg
  configured module search path = ['/ansible/library']
#

**Comment by drgeb** [comment]
Ok following your steps this worked!! Thanks!!
