### ISSUE TITLE
Ansible Container Roles

### ISSUE THREAD

**Issue by chouseknecht** [ansible/ansible-container#218]
We should begin thinking about sharing Ansible Container projects as roles, such that they can be imported into Galaxy and downloaded directly by Ansible Container. To make this happen I purpose the following:

### Ansible Container `init`:

- Add a --role option, that supports packaging the project in a role.
- If `--role`, create a `meta` directory and add to it a `main.yml` file with sane defaults. This is the same `meta/main.yml` file used in Ansible roles.
- ~~Add a new flag to meta/main.yml indicating the role is an Ansible Container project.  We can add a flag without impacting Galaxy.~~
- If `--role`, create a `tasks` directory and add to it a `main.yml` file with a single task. The task will be `command: ansible-container run`. If the role were invoked by Ansible Playbook and Ansible Container is installed, the project will be built, and containers will be instantiated.

### Ansible Container `run`

- Make `run` smart enough to detect when a `build` is needed (because images are not available), and when a `build` is required, have it perform the `build`, and then perform `run`. 

- Add a new command line option `--role`, allowing the user to provide the name of an Ansible Role. Ansible Container will find the role, check that ~~it has a meta/main.yml file with the Ansible Container flag set~~ an `ansible/container.yml`, and execute `build` when images are not present, and then execute `run`.

- Make Ansible Container follow the same strategy for finding roles as Ansible Playbook, which means it should be smart enough to read an `ansible.cfg` file to get the `roles_path` setting.
 
- When the role specified via `--role` cannot be found, Ansible Container should download the role from Ansible Galaxy to the correct roles path, `build` it and `run` it.

**Comment by j00bar** [comment]
Superseded by #221
