### ISSUE TITLE
Missing container.docker module when you install the ansible-container

### ISSUE THREAD

**Issue by sidharthsurana** [ansible/ansible-container#22]
after installing ansible-container cli I ran into following error:

> ansible-container build
No module named docker.engine

The fix for this issue is posted https://github.com/ansible/ansible-container/pull/21

**Comment by pyro2927** [comment]
Also having this issue.

**OS:** OS X 10.11.5
**Ansible Version:** 2.1.0.0

**Comment by chouseknecht** [comment]
Merged https://github.com/ansible/ansible-container/pull/21. This should be fixed now.
