### ISSUE TITLE
Ansible Galaxy integration

### ISSUE THREAD

**Issue by j00bar** [ansible/ansible-container#221]
After a meeting of the minds, we propose the following approach to better leverage and integrate Ansible Container with Ansible Galaxy. This issue supersedes #218 and #220.

A "container-ready" role is an Ansible role designed for use with Ansible Container to build a particular container for a particular function. Consider it equivalent to a Dockerfile on Docker Hub. It is identifiable by the presence of a file `meta/container.yml` in the role, which contains boilerplate yml for the service as described in the `ansible/container.yml`. For example, a container-ready role derived from our "example" project might have as its `meta/container.yml` these lines only: https://github.com/ansible/ansible-container/blob/c4e32f0fbea61881d88f02688426e0dc23ff16a2/example/ansible/container.yml#L3-L18

We propose adding a designation in Ansible Galaxy for a container-ready role, based on the presence of this file.

We propose a new first-class object in Ansible Galaxy for an Ansible Container Application. Instead of pointing to a VCS repository containing an Ansible Role, it would point to a VCS repository that contained an Ansible Container ready application, complete with `ansible/container.yml` and `ansible/main.yml`.

We propose adding a new command to Ansible Container: `install`. This command will take a reference to an Ansible Galaxy role or to a `requirements.yml` file. It will then perform the following actions:
- Fetch the role's code from VCS and store it in temporary space.
- Read the role's `meta/container.yml` and insert it into the project's `ansible/container.yml` as another service. Best practices would suggest that this snippet contain:
  - An `environment` section with all of the runtime significant environment variables that can be configured
  - The ports, volumes, command, and development environment overrides for this container.
- Read the role's `defaults/main.yml` and insert into the project's `ansible/main.yml` a new play that:
  - Has a `hosts` value of the name of the service from the `meta/container.yml`
  - Has a `vars` list of all of the variables and their default values
  - Has a `roles` value of the name of the role
- Add the role's reference to `ansible/requirements.yml` if the command was invoked naming a Galaxy role

We propose that the build process in `ansible-container build` do an `ansible-galaxy install -r requirements.yml` if that file is present, prior to its run of `ansible-playbook`.

We propose adding a new argument to `ansible-container init` to point to the new first-class object in Ansible Galaxy and initialize a new project from that referenced repository.

**Benefits of this approach:**
1. To re-use an image off of Docker Hub, you have to read and understand a README file about the knobs, dials, and interfaces for that container. With this approach, both the build-time parameters and run-time parameters are all clearly enumerated for the user to tweak.
2. Re-use of the tried and true Ansible role format without any modifications.
3. Enable users to both download the skeleton of a complete containerized application (like the Nulecule specification wanted to do) as well as add-on additional pieces as an application evolves.
4. Enable extremely quick spin-up of new projects, even for users entirely unfamiliar with Ansible or containers.

Comments/concerns welcome. Thanks to @chouseknecht and @gregdek for working with me on this.

**Comment by chouseknecht** [comment]
I'm starting work on the following in order to complete the first pass at our `reuse existing content` story:

>We propose that the build process in ansible-container build do an ansible-galaxy install -r requirements.yml if that file is present, prior to its run of ansible-playbook.

For release 0.2.0 a user will be able to easily reuse existing content by using:

-`--with-volumes` to access roles stored on the file system
-`requirements.yml` to access roles from VCS

For the next release we'll add the other points enumerated above to make Galaxy content more Ansible Container aware.

**Comment by gregdek** [comment]
Implemented!
