### ISSUE TITLE
Define variable in build context that says we're in Ansible Container

### ISSUE THREAD

**Issue by j00bar** [ansible/ansible-container#222]
A role might want to gate certain logic based on whether we're building as part of Ansible Container or not. There should be an environment variable or fact available in the context of Ansible Container that is defined when we are.

**Comment by chouseknecht** [comment]
Adding ANSIBLE_CONTAINER env variable to the build container and all containers on which `main.yml` will operate - https://github.com/ansible/ansible-container/pull/232

**Comment by j00bar** [comment]
Fixed in #232
