### ISSUE TITLE
Better UX for locally stored roles

### ISSUE THREAD

**Issue by j00bar** [ansible/ansible-container#223]
Roles in the `ansible/roles/` path are great, but sometimes users have roles that live on disk outside of the project. That's totally cool and consistent with our best practices. Users can currently mount these inside of the container build process using `--with-volumes`, but it would be great if we provided a shortcut parameter `--roles-path` that:

- Mounted the specified paths into the build container as read-only mounts
- Added to the generated compose specification an `ANSIBLE_ROLES_PATH` environment variable value that enumerated these paths
- Supported both space-separated values (like `--with-volumes`) and colon-separated values (like `roles_path`)

**Comment by dustymabe** [comment]
> Roles in the ansible/roles/ path are great, but sometimes users have roles that live on disk outside of the project.

Is this consistent with what you said in 
https://github.com/ansible/ansible-container/issues/217#issuecomment-245966619 ?

**Comment by j00bar** [comment]
@dustymabe Yes. Playbook != role. The playbook should track the project. Roles can be passed by reference, requirements.yml, etc.
