### ISSUE TITLE
Add Docker support to Ansible synchronize module

### ISSUE THREAD

**Issue by chouseknecht** [ansible/ansible-container#226]
rsync works with Docker:

```
$ rsync -e 'docker -H 192.168.99.100:2376 --tls exec -i' -av --blocking-io openshift.zip grave_yalow:/
building file list ... done
openshift.zip

sent 18925438 bytes  received 42 bytes  12616986.67 bytes/sec
total size is 18922993  speedup is 1.00
```

To make this work for Ansible Container: 
- install rsync in the build image

In Ansible: 
- Modify synchronize action plugin, as it denies connections from docker plugin.
- May need to update parsing/mod_args.py, as it does not allow extra args for the synchronize module.
  the user will either have to know how to construct `docker -H 192.168.99.100:2376 --tls exec -i`, or we’ll need to construct it for them by inspecting $DOCKER_HOST, $DOCKER_TLS_VERIFY.
- Synchronize modules constructs the command as `cmd += " --rsh 'ssh %s %s -o Port=%s'" % (private_key, ssh_opts, dest_port)`. It obviously needs to not do that when we’re using the connection plugin. Since there is an action plugin involved, it can signal to the module that the connection type is docker, and the module construct the above `rsync` command.
- Add the docker connection options (same as what’s in lib/ansible/module_utils/docker_common.py) to the synchronize module, and modify it to construct the `docker exec` portion of the command

Reference: https://github.com/docker/docker/issues/13660

**Comment by Yannig** [comment]
@chouseknecht any comment against my PR?

**Comment by j00bar** [comment]
@Yannig Thanks for the PR. I nudged the core team to take a look at it. 2.2 is already in feature freeze, but it should go into devel after it gets shipped.

**Comment by AndydeCleyre** [comment]
Yes, please! The `copy` module is unbearably slow when dumping in a > 100 MB repo.

**Comment by chouseknecht** [comment]
Attempting now to install the PR into a local build container and test. Will report back. If it looks good, I'll see if we can move it forward on the Ansible project side.

**Comment by chouseknecht** [comment]
Looks good! PR merged. Will bake this into new ansible/ansible-container-builder:0.3 image shortly.

**Comment by chouseknecht** [comment]
I'm finding synchronize only works when you build from scratch. It works on the first build, and then false on subsequent builds. Disappointing, but better than nothing. I tried adding `rsync_opts: --blocking-io`, but that didn't fix it.

**Comment by chouseknecht** [comment]
Fixed synchronize action plugin:

- rsync_opts is now handled as a list, which matches the type expected by the module
- `--rsh docker exec...` is now appended to rsync_opts, respecting values passed by the playbook
- '--blocking-io' is appended to options, if not passed by the module 

Pushed a new ansible/ansible-container-version:0.3 image to Docker Hub that includes Ansible 2.3 commit 65491cc839, the latest synchronize changes 

Tested repeated builds of the demo project, and it works perfectly.
