### ISSUE TITLE
docker connection plugin - could we use docker-py ? 

### ISSUE THREAD

**Issue by dustymabe** [ansible/ansible-container#240]
Just wanted to have a discussion here about the docker connection plugin in ansible. I realize this subject is about a "core" component of ansible and not of ansible-container, but I think we can at least have a discussion about it here. 

If it were possible to run the exec command through [docker-py](https://docker-py.readthedocs.io/en/latest/api/#exec_create) then we could simply make the requirement be that docker-py is installed and not the entirety of the docker engine. 

One example where this would be useful is right [here](https://github.com/ansible/ansible-container/blob/1eb891d8a34160a305c11c46f004002cf78782ad/container/templates/ansible-dockerfile.j2#L9) in ansible-container where we are installing all of docker into the container builder image. Instead of installing all of this we could simply install the thin python library and get the same functionality.

thoughts?

**Comment by j00bar** [comment]
That would be awesome, but we'd still need the docker connection plugin to support docker-py versus the subprocess. If you're wanting to do the work and get it into core, I'm totally happy ditching the docker package from the build container.

**Comment by dustymabe** [comment]
After talking with bcoca in irc today I opened https://github.com/ansible/ansible/issues/17692 to discuss this their with the plugin authors.

**Comment by gregdek** [comment]
Closing now that this feature request exists in core.
