### ISSUE TITLE
tests fail for me when contacting older docker server version

### ISSUE THREAD

**Issue by dustymabe** [ansible/ansible-container#244]
Similar to what we did [here](https://github.com/ansible/ansible-container/commit/80a7a5000ffcbcb6757979dc7ccaca0ce70976aa#diff-
e208f3f3c221c512d250c28a93d212c8R590) we need to set the DOCKER_API_VERSION variable in tests where we call the docker cli directly: one example is here: https://github.com/ansible/ansible-container/blob/2cad05d4f944c2aa5212105ad010eb7cdd0db90c/test/integration/test_slow.py#L26

In my case I was talking to a docker server that only talked 1.22 so I had to change it to something like this to get it to work: 
```
result = env.run('env', 'DOCKER_API_VERSION=1.22', 'docker', 'inspect', .....
```

we need to make this generic and set it or otherwise account for this.

**Comment by chouseknecht** [comment]
This may no longer be an issue. I updated ansible-dockerfile.j2 to install a newer version of docker-engine. Tests seem to be working consistently both locally and on Travis.

**Comment by dustymabe** [comment]
I didn't know about 'auto' - why wouldn't this be the default behavior of the docker client... sigh.

**Comment by dustymabe** [comment]
turns out DOCKER_API_VERSION=auto only works for docker-py I believe
