### ISSUE TITLE
Do we need to generate roles with shipit?

### ISSUE THREAD

**Issue by containscafeine** [ansible/ansible-container#266]
With #233 we are trying to leverage `kompose` to do the conversion part of `shipit`. I have implemented that with `shipit kube/openshift --save-config` in #239, but the role generation is still handled by ansible container itself.

I have not looked into it if the artifacts being generated by kompose can be reused by roles, but even if they can be, do we want to generate roles using shipit or just spit out the artifacts which the user can take deploy using `kubectl/oc create -f` instead of having to maintain conversion and role generation, both?

Does generating roles add any value?

Just thinking out loud. Thoughts? @chouseknecht @j00bar @dustymabe

**Comment by chouseknecht** [comment]
We talked about this with @gregdek and what we decided was....

- Use k-om-pose to create a new container/kompose engine capable of deploying directly to kubernetes, openshift, etc.

- Leave `shipit` alone. When new Ansible modules become available for k8s and openshift, `shipit` will be updated accordingly.

Thought @j00bar wrote this up in an issue, but I can't find it, so here it is.

**Comment by containscafeine** [comment]
Oh, I'm a bit confused about this :(

> Use k-om-pose to create a new container/kompose engine capable of deploying directly to kubernetes, openshift, etc.

Does this relate to #152? Is this about using kompose + xyz kubernetes/openshift python library?

> Leave `shipit` alone. When new Ansible modules become available for k8s and openshift, shipit will be updated accordingly.

Does that mean ansible container will continue to do the required conversion for `shipit`and `shipit --save-config` and not use `kompose` for the same?

**Comment by gregdek** [comment]
Here's the point @containscafeine -- there's a lot of moving parts in the Kube universe right now. Several tools are trying to figure out the docker-compose->kubernetes transformation. Clearly lots of overlap between shipit and kompose.

We're basically leaving shipit alone for now because it works well enough for some people to get value out of it, but in the long term, it's likely that kompose will be the method of choice for turning "docker compose-ish" into "kubernetes-ish". Which is the primary use case for shipit.

Does spitting out roles from shipit add value? Dunno. Are you proposing that we dump the role generation option? That's fine, and maybe we will, but we're not ready to do that yet. For now, we're leaving shipit alone and focusing on improving the build end of the tool.

**Comment by dustymabe** [comment]
I think he was just trying to figure out where kompose fit in. when we first started the conversation we were talking about replacing "shipit" with kompose guts so that is what shubham was working off of.

It does make sense to implement this outside of shipit if there are people already using shipit.

**Comment by containscafeine** [comment]
Hey @gregdek,

> We're basically leaving shipit alone for now because it works well enough for some people to get value out of it

Agree, but not sure how does making `kompose` do `shipit` things change this? It's still going to spit out the same artifacts, and going to add value because it supports more conversion directives than what shipit supports today, and also supports Compose v2.

Yes, there are a lot of tools which are working to convert docker compose to kubernetes right now, but `kompose` has upstream Kubernetes, Red Hat and Skippbox communities backing it full time, and is under active development. It's going to stay for good.

The biggest motivator for me to introduce `kompose` for doing `shipit` stuff is that it is going to make supporting Compose v2 a breeze, without having to maintain the conversion inside the project, which has been probably the most requested feature since ansible container got out (see #67) and removes the barrier to entry completely.

> Are you proposing that we dump the role generation option?

Well, if the roles can reuse kubernetes/openshift artifacts generated by kompose, couldn't be better, but if not, then the conversion has to be done all over again, so _maybe_ roles could go.

I might have blabbered, but if `kompose` gives us Compose v1 and v2 conversion today, then why not?

WDYT?

**Comment by gregdek** [comment]
Looking closer, doesn't this discussion all make more sense in the context of #239 itself?

**Comment by gregdek** [comment]
I mean, that's great work on #239, and it's essentially rewriting shipit. Which, from what I can tell, is probably moving us in the right direction -- but we're trying to drop 0.2 and just leave the shipit bits alone for now. I would recommend letting us get 0.2 out the door this week and then getting together to talk about #239 and its fuller ramifications, just to make sure we'll all on the same page.

**Comment by containscafeine** [comment]
> Looking closer, doesn't this discussion all make more sense in the context of #239 itself?

Yes, it does. If #239 goes in, then the provider(k8s/oc) artifacts and the roles generated by `shipit <provider> --save-config` will be inconsistent with each other because the former will be generated by kompose and latter by ansible container, hence the question if generating roles was necessary at all.

> I would recommend letting us get 0.2 out the door this week and then getting together to talk about #239 and its fuller ramifications, just to make sure we'll all on the same page.

Makes sense :)

**Comment by gregdek** [comment]
OK. I'll close this and we'll give #239 a close look after 0.2 releases. We'll also get together to flesh out other roadmappy things.
