### ISSUE TITLE
Docker beta support?

### ISSUE THREAD

**Issue by my2ter** [ansible/ansible-container#27]
Hi,

The project is dependent on Docker Toolbox library (docker-compose) and therefore wouldn't benefit from the new xhyve VM.

Do you have any ideas how this would be possible?

Cheers,

**Comment by j00bar** [comment]
Howdy!

We've made the engine/orchestrator specific parts of the code modular. If you'd like to implement a subclass of `container/engine.py:BaseEngine` as `container/xhyve/engine.py`, we'll be happy to review and include it. Thanks!

-jag

**Comment by my2ter** [comment]
@j00bar 

Hey mate, I wish I had time to get back to python and contribute but it won't happen anytime soon I'm afraid.

I highly recommend you implement it sooner rather than later tho. The native implementation of Docker with OS X is the way to go imo.

Cheers.

**Comment by geerlingguy** [comment]
@my2ter - I agree it would be great to have this support in as soon as possible... is the Docker for Mac/Windows private beta finally not private? Last time I tried a month or two ago, I still couldn't use it because it required an invite. I had signed up for the list the day the beta was announced, but still can't get it on my Mac.

**Comment by sebinjohn** [comment]
I was able to run a small build successfully by mounting the `/var/run/docker.sock:/var/run/docker.sock` the change was done in  `container/templates/build-docker-compose.j2.yml`

**Comment by Blackbaud-IanThomas** [comment]
@sebinjohn Are you saying that you were able to get a build working with Docker for Mac with a small change?  What does that change look like?

**Comment by j00bar** [comment]
Let me explain what's going on, folks...

The builder container calls back out to the Docker daemon to talk to the other containers. The preferred way to do this is TCP+TLS, which is what we describe here: https://docs.ansible.com/ansible-container/installation.html#configuring-docker - What @sebinjohn's workaround describes is doing that via another means: mounting the UNIX socket inside of the builder container.

Really, the best thing to do is to configure your Docker daemon with TCP+TLS and ensure that you set the proper environment variables in the environment from which you're calling Ansible Container: DOCKER_HOST, DOCKER_TLS_VERIFY, and DOCKER_CERT_PATH.

**Comment by sebinjohn** [comment]
@Blackbaud-IanThomas Take  a look at https://github.com/sebinjohn/ansible-container/pull/1/files to see the changes I made.

**Comment by sebinjohn** [comment]
@j00bar  Good that you explained it. I just started with docker mac beta yesterday. Have you configured it to use TCP+TLS?

**Comment by j00bar** [comment]
@sebinjohn Taking it for a spin now.

**Comment by Blackbaud-IanThomas** [comment]
This is good to see.  @sebinjohn, I might try mounting the docker socket like you did in the short term just to see the workflow, but I'm definitely looking forward to seeing what it looks like with TCP+TLS. Thanks @j00bar!

**Comment by splisson-altair** [comment]
I asked Docker team, Docker for Mac beta does not allow to configure it to use TCP instead of socket.
For now I'm using a socat trick:
docker run -d -v /var/run/docker.sock:/var/run/docker.sock -p 0.0.0.0:1234:1234 bobrik/socat TCP-LISTEN:1234,fork UNIX-CONNECT:/var/run/docker.sock

I'll try mounting the docker sock as @sebinjohn suggested

**Comment by j00bar** [comment]
The most recent commit enables use of the UNIX socket if the DOCKER_HOST variable isn't set. I got this successfully working with Docker for Mac, but Docker Machine with Docker for Mac still appears kinda janky.
