### ISSUE TITLE
ansible_container shipit provider

### ISSUE THREAD

**Issue by ivotron** [ansible/ansible-container#278]
##### ISSUE TYPE
- Feature Idea
##### SUMMARY

Have a `docker_container`-based `shipit` provider

**Comment by chouseknecht** [comment]
@ivotron,

Thank you for your interest in Ansible Container, and a sincere thank-you for taking the time to suggest this feature. 

I'm not sure that the `docker_container` module is a good candidate for a ShipIt engine. The point of ShipIt is deploying containers to the cloud, which is not at all what `docker_container` does.

But... maybe what you're getting at is a Swarm engine?

**Comment by ivotron** [comment]
What I have in mind is the ability of being able to deploy containers to a cluster of docker hosts with ansible. That was actually the first thing that came to my mind when I heard about `ansible-container`. I thought "awesome! I can deploy containers with the same simplicity associated to ansible (i.e. only python and ssh required)". Would that be another entirely different project?

**Comment by j00bar** [comment]
In your use case, how would you handle things such as volumes, network ports, and all of the other sorts of features systems like swarm/kubes exist to provide?

**Comment by j00bar** [comment]
Howdy, @ivotron - still interested how you'd envision things like volumes and network ports being handled in your use case across Docker hosts....

**Comment by ivotron** [comment]
Hi @j00bar, I don't know how one would go about handling things like overlay networks. What I had in mind for this ansible-based deployment engine is very simple: given a list of containers grouped in docker-compose-like services (or pods, in kubernetes lingo), deploy them in a cluster of docker hosts without needing agents, just ssh+python.

Maybe, initially, the assumption is that users are responsible for making sure that services don't colide w.r.t. networking ports and volumes (or maybe the generated playbooks could check that this doesn't have). Just having some automation in terms of bringing services up on a cluster, possibly with the option of specifying simple scheduling policies, would be really useful.

**Comment by ivotron** [comment]
Hi @j00bar, I don't know how one would go about handling things like
overlay networks. What I had in mind for this ansible-based deployment
engine is very simple: given a list of containers grouped in
docker-compose-like services (or pods, in kubernetes lingo), deploy them in
a cluster of docker hosts without needing agents, just ssh+python.

Maybe, initially, the assumption is that users are responsible for making
sure that services don't colide w.r.t. networking ports and volumes (or
maybe the generated playbooks could check that this doesn't have). Just
having some automation in terms of bringing services up on a cluster,
possibly with the option of specifying simple scheduling policies, would be
really useful.

**Comment by gregdek** [comment]
@ivotron Thanks for the input. I think what you're proposing out of scope for this project for the reasons mentioned above -- closing this feature idea.
