### ISSUE TITLE
volume not created/mounted properly

### ISSUE THREAD

**Issue by rokroskar** [ansible/ansible-container#298]
I'm not sure this is the correct place to ask this question, but I can't find any documentation about this anywhere: 

with a previous version of `ansible-container` (I believe 0.1) I included a line like this in my `container.yml`:

```yaml
services: 
...
...
    volumes: 
      - vol1
```

On the host, this created a directory `/var/lib/docker/volumes/<project-name>_vol1` and I have been happily reading and writing from this directory inside the container. 

However, I now tried to add a second persistent volume:

```yaml
services: 
... 
... 
    volumes: 
      - vol1
      - vol2
```

Now, `ansible-container build` doesn't create a directory `/var/lib/docker/volumes/<project-name>_vol2` but instead it creates a volume with a random hash as a name. In addition, the ansible tasks that should add some directories to this volume complete without error, but the directories are not created. In fact what seems to be happening is that the directories are made in one volume during the build, but then a second volume is created when I actually run the container and it's obviously empty. If I make a volume called `/var/lib/docker/volumes/<project-name>_vol2` by hand it also doesn't seem to recognize it, creating a new volume instead. What am I missing here?

**Comment by chouseknecht** [comment]
Ansible Container just passes the volumes off to Docker Compose, so whatever happens with non-specific volume mappings is up to Docker.  However, Ansible Container operates from a temp directory, so maybe using a temp directory is breaking this functionality in some way.

If it's an issue with running from the temp directory, the fix might be for Ansible Container to transform '-vol1' to something like '${PWD}:/var/lib/docker/volumes< basename($PWD)>_vol1'.

Or.. you could of course just explicitly map the project volume to a path in the container.

What version of Docker are you running?

**Comment by rokroskar** [comment]
right, that makes sense. An explicit mapping would probably be best. It's really puzzling why it works for one of the volumes and not the other.

**Comment by rokroskar** [comment]
Sorry, forgot to say: 

```
Docker version 1.10.3, build 5206701-unsupported
```

**Comment by gregdek** [comment]
Looks like this question was answered, thanks @rokroskar and @chouseknecht, closing

**Comment by HackerMD** [comment]
I am having a similar problem and was hoping that you could provide some insight into the use of the `volumes` directive.

I am using the following configuration in `container.yml` for `ansible-container` (0.3 installed from source):

```yaml

version: '2'

volumes:
  my-volume: {}

services:
  storage:
    volumes:
      - my-volume:/storage
  db:
    volumes_from:
      - my-volume
```

Based on the [ansible-container](https://docs.ansible.com/ansible-container/container_yml/reference.html#volumes) and [docker-compose](https://docs.docker.com/compose/compose-file/compose-file-v2/#/volume-configuration-reference) documentation, I assume that this creates a [data volume container](https://docs.docker.com/engine/tutorials/dockervolumes/#/creating-and-mounting-a-data-volume-container) and a named volume `my-volume`, which should be accessible from other services via [volumes_from](https://docs.ansible.com/ansible-container/container_yml/reference.html#volumes-from).

When I check volumes, I get the following:

```
$ docker volume ls                                                                                                                                                         
DRIVER              VOLUME NAME
local               ansible_my-volume
```

```
$ docker inspect ansible_my-volume                                                                                                                          
[
    {
        "Driver": "local",
        "Labels": null,
        "Mountpoint": "/var/lib/docker/volumes/ansible_my-volume/_data",
        "Name": "ansible_my-volume",
        "Options": {},
        "Scope": "local"
    }
]
```

The `ansible_my-volume` volume persists after `build` has completed successfully, but `my-volume` gets never created.

The docker documentation on [data volumes](https://docs.docker.com/engine/tutorials/dockervolumes/#/data-volumes) states the following:

> Volumes are initialized when a container is created. If the container’s base image contains data at the specified mount point, that existing data is copied into the new volume upon volume initialization.

What am I missing?

My environment:

```
ansible (2.2.1.0)
ansible-container (0.3.0rc0)
docker (2.1.0)
docker-compose (1.11.2)
docker-py (1.10.6)
docker-pycreds (0.2.1)
dockerpty (0.4.1)
```
