### ISSUE TITLE
Roadmap status?

### ISSUE THREAD

**Issue by nonotest** [ansible/ansible-container#305]
##### ISSUE TYPE

 - Documentation Report

Hello,

Just wondering what is the current status with the roadmap.
Have all the items in the current document been completed for v0.2?
Are you now working on a v0.3? If yes what would be the feature list?

Couldn't find any information..

Thanks!

**Comment by chouseknecht** [comment]
A roadmap for 0.3.0 has not been published. One if forthcoming. Things we are working on:

- implementing compose v2 (see proposal [here](https://github.com/ansible/ansible-container/blob/develop/proposals/compose-v2.md))
- adopting [kompose](https://github.com/kubernetes-incubator/kompose) as a way to translate container.yml to kubernetes resources
- implementing a build cache using a custom Ansible execution strategy
