### ISSUE TITLE
Nightly builds

### ISSUE THREAD

**Issue by gregdek** [ansible/ansible-container#332]
Nightly builds should happen for the following and be readily available:

* pip install ansible-container-nightly-version
* docker builder image
* end-to-end demo

**Comment by gregdek** [comment]
Definitely want to build the demo project every night, and that's just a galaxy role

We also want to build the docker image every night

Maybe we want to push to pypi less often?

**Comment by ryansb** [comment]
TravisCI supports cronjobs now, so that could handle nightly builds. https://docs.travis-ci.com/user/cron-jobs/

**Comment by chouseknecht** [comment]
Done and done. 

Setup the TravisCI cron jobs to run daily for:

- github.com/ansible/ansible-container-demo 
- github.com/ansible/django-gulp-nginx
- github.com/ansible/nginx-container

And configured notifications to the #containers channel on Slack.
