### ISSUE TITLE
Override in container.yml for Ansible Vault variables

### ISSUE THREAD

**Issue by JJediny** [ansible/ansible-container#345]
In our roles we define variables with {{ vault.foo.bar }}. Do variables set in container.yml override these ENV variables/lookups by default? In other word's can anyone declare the KEY= (for the Key=Value) in container.yml and add the Value at runtime? that value that is otherwise encrypted by vault; without modifying code in their `role?`.

If not it would make sense to have an override in container.yml for vault variables

**Comment by chouseknecht** [comment]
Variables defined for `container.yml` are separate from variables passed to `ansible-playbook` and defined in your role. So if in the role you have {{ vault.foo.bar }}, you can set that value a couple different ways. 

You could create an environment variable VAULT_FOO_BAR, for example, and pass it into the `build` command using [--with-variables](http://docs.ansible.com/ansible-container/reference/build.html). That would look `ansible-container --with-variables VAULT_FOO_BAR=some_value build`, and it would define the variable inside the build container, making it accessible in `main.yml` using `{{ lookup('env', 'VAULT_FOO_BAR') }}`.

You could use `--` to pass parameters to `ansible-playbook` directly. For example:

```
ansible-playbook build -- \
   --extra-vars "@/etc/ansible/vault.yml" \
   --vault-password-file ~/.vault_pass.py
```

**Comment by chouseknecht** [comment]
I've thought about enabling Ansible Container to decrypt a vault file. There's a downside, however. When you start adding secretes to services in your `container.yml` as environment variables, those variables are not secure. They potentially get added to the image, unless you use `--flatten`, and they also become easily discoverable just by inspecting the container.

Encouraging the transmission of secrets by way of environment variables inside `contianer.yml` seems like a bad idea in the long run. We need a solution that is actually secure, and we need a solution that aligns with k8s.

In k8s there is the concept of secrets, and there's also a new thing called an [Init container](http://kubernetes.io/docs/user-guide/pods/init-container/), which can access secrets separately from the application containers. IMHO, we will be better served, if we can find a way to incorporate these concepts into Ansible Container.

**Comment by chouseknecht** [comment]
Closing this for now. We will open an issue at some point to track things related to secrets and init containers.
