### ISSUE TITLE
cannot run a single ansible container anymore: cannot import name errors

### ISSUE THREAD

**Issue by JeanFrancoisMaes** [ansible/ansible-container#361]
##### ISSUE TYPE

 - Bug Report

##### container.yml 

```
irrelevant
```

##### main.yml 

```
irrelevant
```

##### OS / ENVIRONMENT

```
Ansible Container, version 0.2.0
Linux, jean-laptop, 4.4.0-59-generic, #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017, x86_64
2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] /usr/bin/python
cannot import name errors
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/container/cli.py", line 212, in commandline
    getattr(engine, u'cmdrun_{}'.format(args.subcommand))(**vars(args))
  File "/usr/local/lib/python2.7/dist-packages/container/engine.py", line 527, in cmdrun_version
    engine_obj = load_engine(**engine_args)
  File "/usr/local/lib/python2.7/dist-packages/container/utils.py", line 101, in load_engine
    mod = importlib.import_module('container.%s.engine' % engine_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/container/docker/engine.py", line 17, in <module>
    from docker.client import errors as docker_errors
ImportError: cannot import name errors
```
##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```

```

**Comment by chouseknecht** [comment]
@JeanFrancoisMaes, apologies for not responding sooner. 

Ansible Container v0.2.0 expects docker 1.8.0 -see [requirements.txt](https://github.com/ansible/ansible-container/blob/release-0.2.0/requirements.txt#L2). 

Ansible Container v0.3.0 expects docker 1.10.6 -see the [requirements.txt](https://github.com/ansible/ansible container/blob/develop/requirements.txt#L2).

We don't currently support docker v2, which I suspect is what you have installed. It appears that v2 stopped importing errors into the client. 

Closing this issue for now, as I am sure we will be adding docker v2 support on a future road map.
