### ISSUE TITLE
invalid header field value "oci runtime error: container_linux.go

### ISSUE THREAD

**Issue by sas22** [ansible/ansible-container#364]
##### ISSUE TYPE

 - Bug Report
 

##### container.yml 

```
version: "1"
services:
  # Add your containers here, specifying the base image you want to build from
  # For example:
  #
  web:
    image: ubuntu:trusty
    ports:
      - "80:80"
    command: ['/usr/bin/dumb-init', '/usr/sbin/apache2ctl', '-D', 'FOREGROUND']
    dev_overrides:
      environment:
        - "DEBUG=1"

registries: {}
  # Add optional registries used for deployment. For example:
  #  google:
  #    url: https://gcr.io
  #    namespace: my-cool-project-xxxxxx

```

##### main.yml 

```
---
- hosts: all
  gather_facts: false

```

##### OS / ENVIRONMENT

```
sh-4.2# ansible-container --debug version
Ansible Container, version 0.2.0
Linux, dcb6cf286c22, 3.10.0-327.22.2.el7.x86_64, #1 SMP Thu Jun 23 17:05:11 UTC 2016, x86_64
2.7.5 (default, Nov  6 2016, 00:28:07)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] /usr/bin/python2
No DOCKER_HOST environment variable found. Assuming UNIX socket at /var/run/docker.sock
{u'Architecture': u'x86_64',
 u'BridgeNfIp6tables': False,
 u'BridgeNfIptables': False,
 u'CPUSet': True,
 u'CPUShares': True,
 u'CgroupDriver': u'cgroupfs',
 u'ClusterAdvertise': u'',
 u'ClusterStore': u'',
 u'Containers': 17,
 u'ContainersPaused': 0,
 u'ContainersRunning': 11,
 u'ContainersStopped': 6,
 u'CpuCfsPeriod': True,
 u'CpuCfsQuota': True,
 u'Debug': False,
 u'DefaultRuntime': u'runc',
 u'DockerRootDir': u'/var/lib/docker',
 u'Driver': u'devicemapper',
 u'DriverStatus': [[u'Pool Name', u'docker-253:0-134478671-pool'],
                   [u'Pool Blocksize', u'65.54 kB'],
                   [u'Base Device Size', u'10.74 GB'],
                   [u'Backing Filesystem', u'xfs'],
                   [u'Data file', u'/dev/loop0'],
                   [u'Metadata file', u'/dev/loop1'],
                   [u'Data Space Used', u'8.101 GB'],
                   [u'Data Space Total', u'107.4 GB'],
                   [u'Data Space Available', u'23.17 GB'],
                   [u'Metadata Space Used', u'15.01 MB'],
                   [u'Metadata Space Total', u'2.147 GB'],
                   [u'Metadata Space Available', u'2.132 GB'],
                   [u'Thin Pool Minimum Free Space', u'10.74 GB'],
                   [u'Udev Sync Supported', u'true'],
                   [u'Deferred Removal Enabled', u'false'],
                   [u'Deferred Deletion Enabled', u'false'],
                   [u'Deferred Deleted Device Count', u'0'],
                   [u'Data loop file',
                    u'/var/lib/docker/devicemapper/devicemapper/data'],
                   [u'Metadata loop file',
                    u'/var/lib/docker/devicemapper/devicemapper/metadata'],
                   [u'Library Version', u'1.02.135-RHEL7 (2016-09-28)']],
 u'ExecutionDriver': u'',
 u'ExperimentalBuild': False,
 u'HttpProxy': u'',
 u'HttpsProxy': u'',
 u'ID': u'COLQ:2VTP:WNPA:ULKQ:5J4E:MUGV:IUJI:Y5HS:LLNT:NZVF:LAX4:AA2U',
 u'IPv4Forwarding': True,
 u'Images': 42,
 u'IndexServerAddress': u'https://index.docker.io/v1/',
 u'KernelMemory': True,
 u'KernelVersion': u'3.10.0-327.22.2.el7.x86_64',
 u'Labels': None,
 u'LiveRestoreEnabled': False,
 u'LoggingDriver': u'json-file',
 u'MemTotal': 3976015872,
 u'MemoryLimit': True,
 u'NCPU': 1,
 u'NEventsListener': 0,
 u'NFd': 109,
 u'NGoroutines': 101,
 u'Name': u'vgs_qc_jenkins.il.nds.com',
 u'NoProxy': u'',
 u'OSType': u'linux',
 u'OomKillDisable': True,
 u'OperatingSystem': u'CentOS Linux 7 (Core)',
 u'Plugins': {u'Authorization': None,
              u'Network': [u'bridge', u'null', u'host', u'overlay'],
              u'Volume': [u'local']},
 u'RegistryConfig': {u'IndexConfigs': {u'docker.io': {u'Mirrors': None,
                                                      u'Name': u'docker.io',
                                                      u'Official': True,
                                                      u'Secure': True}},
                     u'InsecureRegistryCIDRs': [u'127.0.0.0/8'],
                     u'Mirrors': None},
 u'Runtimes': {u'runc': {u'path': u'docker-runc'}},
 u'SecurityOptions': [u'seccomp'],
 u'ServerVersion': u'1.12.6',
 u'SwapLimit': True,
 u'Swarm': {u'Cluster': {u'CreatedAt': u'0001-01-01T00:00:00Z',
                         u'ID': u'',
                         u'Spec': {u'CAConfig': {},
                                   u'Dispatcher': {},
                                   u'Orchestration': {},
                                   u'Raft': {},
                                   u'TaskDefaults': {}},
                         u'UpdatedAt': u'0001-01-01T00:00:00Z',
                         u'Version': {}},
            u'ControlAvailable': False,
            u'Error': u'',
            u'LocalNodeState': u'inactive',
            u'Managers': 0,
            u'NodeAddr': u'',
            u'NodeID': u'',
            u'Nodes': 0,
            u'RemoteManagers': None},
 u'SystemStatus': None,
 u'SystemTime': u'2017-01-27T10:45:22.218753362+02:00'}
{u'ApiVersion': u'1.24',
 u'Arch': u'amd64',
 u'BuildTime': u'2017-01-10T20:20:01.213950987+00:00',
 u'GitCommit': u'78d1802',
 u'GoVersion': u'go1.6.4',
 u'KernelVersion': u'3.10.0-327.22.2.el7.x86_64',
 u'Os': u'linux',
 u'Version': u'1.12.6'}

```
##### SUMMARY

I am trying to invoke ansible-container from within a docker (not docker-in-docker style, rather the suggested option to connect to the docker socket).

I get the following error:
ERROR: for ansible-container  invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"chdir to cwd (\\\"/ansible-container/ansible\\\") set in config.json failed: no such file or directory\"\n"

##### STEPS TO REPRODUCE

```
as a start i took a simple 'ansible-container init' project, and uncomment that ansible/container.yml example. simple invocation on the host machine was ok. but when i invoked it from a docker container it had this error. any assist is welcome. thanks.
```

##### EXPECTED RESULTS

i would expec that invoking ansible-container from within a docker container connected to the docker-engine on the host machine will work, but from some reason the workdir of the ansible-container-builder does not recognize the context /ansible-container/ansible path.
##### ACTUAL RESULTS

docker run -v /var/run/docker.sock:/var/run/docker.sock -it  --entrypoint=/bin/sh <image-id>

sh-4.2# ansible-container init
Ansible Container initialized.

sh-4.2# ansible-container build
No DOCKER_HOST environment variable found. Assuming UNIX socket at /var/run/docker.sock
Starting Docker Compose engine to build your images...

ERROR: for ansible-container  invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"chdir to cwd (\\\"/ansible-container/ansible\\\") set in config.json failed: no such file or directory\"\n"
Attaching to
Cleaning up Ansible Container builder...

ERROR: for ansible-container  invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"chdir to cwd (\\\"/ansible-container/ansible\\\") set in config.json failed: no such file or directory\"\n"
Attaching to
Cleaning up Ansible Container builder...
No image found for tag scripts-web:latest, so building from scratch

ERROR: for web  invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"/usr/bin/dumb-init\\\": stat /usr/bin/dumb-init: no such file or directory\"\n"

ERROR: for ansible-container  invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"chdir to cwd (\\\"/ansible-container/ansible\\\") set in config.json failed: no such file or directory\"\n"
Attaching to
Aborting on container exit...
Ansible playbook run failed.
Cleaning up Ansible Container builder...
Ansible build failed

```

```

**Comment by sas22** [comment]
i also tried to run the inner container with --priveledged mode. the provided env is from within the container. 
The host on which this docker runs has the following environment 
`[root@vgs_qc_jenkins ~]# ansible-container --debug version
Ansible Container, version 0.2.0
Linux, vgs_qc_jenkins.il.nds.com, 3.10.0-327.22.2.el7.x86_64, #1 SMP Thu Jun 23 17:05:11 UTC 2016, x86_64
2.7.5 (default, Nov  6 2016, 00:28:07)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] /usr/bin/python
No DOCKER_HOST environment variable found. Assuming UNIX socket at /var/run/docker.sock
{u'Architecture': u'x86_64',
 u'BridgeNfIp6tables': False,
 u'BridgeNfIptables': False,
 u'CPUSet': True,
 u'CPUShares': True,
 u'CgroupDriver': u'cgroupfs',
 u'ClusterAdvertise': u'',
 u'ClusterStore': u'',
 u'Containers': 17,
 u'ContainersPaused': 0,
 u'ContainersRunning': 10,
 u'ContainersStopped': 7,
 u'CpuCfsPeriod': True,
 u'CpuCfsQuota': True,
 u'Debug': False,
 u'DefaultRuntime': u'runc',
 u'DockerRootDir': u'/var/lib/docker',
 u'Driver': u'devicemapper',
 u'DriverStatus': [[u'Pool Name', u'docker-253:0-134478671-pool'],
                   [u'Pool Blocksize', u'65.54 kB'],
                   [u'Base Device Size', u'10.74 GB'],
                   [u'Backing Filesystem', u'xfs'],
                   [u'Data file', u'/dev/loop0'],
                   [u'Metadata file', u'/dev/loop1'],
                   [u'Data Space Used', u'8.105 GB'],
                   [u'Data Space Total', u'107.4 GB'],
                   [u'Data Space Available', u'23.16 GB'],
                   [u'Metadata Space Used', u'15.03 MB'],
                   [u'Metadata Space Total', u'2.147 GB'],
                   [u'Metadata Space Available', u'2.132 GB'],
                   [u'Thin Pool Minimum Free Space', u'10.74 GB'],
                   [u'Udev Sync Supported', u'true'],
                   [u'Deferred Removal Enabled', u'false'],
                   [u'Deferred Deletion Enabled', u'false'],
                   [u'Deferred Deleted Device Count', u'0'],
                   [u'Data loop file',
                    u'/var/lib/docker/devicemapper/devicemapper/data'],
                   [u'Metadata loop file',
                    u'/var/lib/docker/devicemapper/devicemapper/metadata'],
                   [u'Library Version', u'1.02.135-RHEL7 (2016-09-28)']],
 u'ExecutionDriver': u'',
 u'ExperimentalBuild': False,
 u'HttpProxy': u'',
 u'HttpsProxy': u'',
 u'ID': u'COLQ:2VTP:WNPA:ULKQ:5J4E:MUGV:IUJI:Y5HS:LLNT:NZVF:LAX4:AA2U',
 u'IPv4Forwarding': True,
 u'Images': 42,
 u'IndexServerAddress': u'https://index.docker.io/v1/',
 u'KernelMemory': True,
 u'KernelVersion': u'3.10.0-327.22.2.el7.x86_64',
 u'Labels': None,
 u'LiveRestoreEnabled': False,
 u'LoggingDriver': u'json-file',
 u'MemTotal': 3976015872,
 u'MemoryLimit': True,
 u'NCPU': 1,
 u'NEventsListener': 0,
 u'NFd': 103,
 u'NGoroutines': 89,
 u'Name': u'vgs_qc_jenkins.il.nds.com',
 u'NoProxy': u'',
 u'OSType': u'linux',
 u'OomKillDisable': True,
 u'OperatingSystem': u'CentOS Linux 7 (Core)',
 u'Plugins': {u'Authorization': None,
              u'Network': [u'overlay', u'bridge', u'null', u'host'],
              u'Volume': [u'local']},
 u'RegistryConfig': {u'IndexConfigs': {u'docker.io': {u'Mirrors': None,
                                                      u'Name': u'docker.io',
                                                      u'Official': True,
                                                      u'Secure': True}},
                     u'InsecureRegistryCIDRs': [u'127.0.0.0/8'],
                     u'Mirrors': None},
 u'Runtimes': {u'runc': {u'path': u'docker-runc'}},
 u'SecurityOptions': [u'seccomp'],
 u'ServerVersion': u'1.12.6',
 u'SwapLimit': True,
 u'Swarm': {u'Cluster': {u'CreatedAt': u'0001-01-01T00:00:00Z',
                         u'ID': u'',
                         u'Spec': {u'CAConfig': {},
                                   u'Dispatcher': {},
                                   u'Orchestration': {},
                                   u'Raft': {},
                                   u'TaskDefaults': {}},
                         u'UpdatedAt': u'0001-01-01T00:00:00Z',
                         u'Version': {}},
            u'ControlAvailable': False,
            u'Error': u'',
            u'LocalNodeState': u'inactive',
            u'Managers': 0,
            u'NodeAddr': u'',
            u'NodeID': u'',
            u'Nodes': 0,
            u'RemoteManagers': None},
 u'SystemStatus': None,
 u'SystemTime': u'2017-01-27T10:52:05.828676343+02:00'}
{u'ApiVersion': u'1.24',
 u'Arch': u'amd64',
 u'BuildTime': u'2017-01-10T20:20:01.213950987+00:00',
 u'GitCommit': u'78d1802',
 u'GoVersion': u'go1.6.4',
 u'KernelVersion': u'3.10.0-327.22.2.el7.x86_64',
 u'Os': u'linux',
 u'Version': u'1.12.6'}
`

**Comment by chouseknecht** [comment]
Thank you for your interest in Ansible Container, and for taking the time to file an issue. Your feedback is important to us. 

Running Ansible Container from inside a container is not currently supported. It's intended to be used outside of a container, from your local command line. You may be able to get it to work from inside a container, but that's not currently a strategy that the project is pursuing.

**Comment by sas22** [comment]
Thanks I understand. Though.. you mentioned 'You may be able to get it to work from inside a container".. could you refer me to correct way of doing that although it is not officially supported?
My intention is to make usage of such images as 'jenkins slave' that once we build a certain component as maven artifact we will already have its docker built after 'package' phase. Otherwise, it will require us to set jenkins slaves with all ansible-container pre-requisite in advance or as vm's templates and we try to  skip such need if possible.
Btw, we really are fans of the ansible-container framework, it makes all our images build mechanism much cleaner than bash-ing all around :+1:  Thanks a lot for that!

**Comment by chouseknecht** [comment]
Now that I think about it, we run our tests inside a container. Take a look at test/run.sh and the test/local project. We build that project, and then run it. I *think* you may be able to model what you're attempting off of the test/local project, but no guarantees.

**Comment by sas22** [comment]
cool. i'll have a look. hopefully be able to come back with good news soon :)

btw, i also encounter 'cleanup' issues. That is if i try to rebuild my component with, say, older version it says an advanced version already is installed. meaning, it doesn't start from clean. so i currently work around this by restart the ansible-container as i'm not sure how the layering is cached by it. if you are interested that i open a detailed issue how to reproduce such a scenario on the way i can do that.
