### ISSUE TITLE
Fixes for minor documentation issues related to OpenShift/Minishift

### ISSUE THREAD

**Issue by gbraad** [ansible/ansible-container#370]
##### ISSUE TYPE
 - Documentation Report

##### SUMMARY
  * #367 
  * #368 
  * #369

**Comment by gbraad** [comment]
If you want, I can merge these changes. I originally did them from a tablet and the Github web interface (painful experience).

**Comment by chouseknecht** [comment]
@gbraad, merged. Thank you for taking the time to fix these!

**Comment by gbraad** [comment]
You're welcome...
