### ISSUE TITLE
Replace main.yml with roles in container.yml

### ISSUE THREAD

**Issue by gregdek** [ansible/ansible-container#376]
From jag's email to ansible-container list of 29 January 2017:

it’s become clearer and clearer that and Ansible Role really is a perfectly apt descriptor for a microservice. Other roles that are "common" between multiple services serve very well in describing image layers. We want to pivot to make that concept clearer in the way Ansible Container works. Therefore, we’re ditching the playbook, main.yml, entirely - and in its place, you’ll specify a list of roles in your container.yml that apply to each service.

**Comment by ryansb** [comment]
I see where this is coming from, but what about vars or similar? Are users expected to set all vars to their final values in roles? It seems like having a playbook (or section of container.yml) where vars files can be included (especially vaulted vars) would be good to have.

**Comment by j00bar** [comment]
@ryansb Agreed completely. We'd talked about how it seemed redundant that we specified build-time vars and run-time vars separately, often repeating themselves. This gives us the opportunity to use the same definitions in `container.yml` for both the build and run.

**Comment by ryansb** [comment]
Yeah, that's sensible. I can imagine build- and run-time differences, but that's what dev_overrides is for, correct?

**Comment by gregdek** [comment]
"And our builds are presently running without providing a playbook, which is great." --jag, 1 March

**Comment by j00bar** [comment]
I'm considering this done and implemented.
