### ISSUE TITLE
Mount Python from Conductor container in target containers during build

### ISSUE THREAD

**Issue by gregdek** [ansible/ansible-container#378]
From jag's email to Ansible Container list of 29 January 2017:

We’ve heard loud and clear that having to have a Python runtime and Ansible module dependencies inside of the target containers is less-than-ideal. So we’re working on making the "builder" container derivable from any distro you want, and mounting its Python virtualenv across to target containers during build-time. This means you won’t have to have a Python runtime in your target container images.

**Comment by gregdek** [comment]
"The mount python from conductor to target containers is also in happy path working condition." --jag, 1 March

**Comment by j00bar** [comment]
I'm considering this done and implemented.

**Comment by strigazi** [comment]
Any pointers to that?
