### ISSUE TITLE
Replace "push" and "shipit" with single command "deploy"

### ISSUE THREAD

**Issue by gregdek** [ansible/ansible-container#379]
From jag email to Ansible Container list on 29 January 2017:

We’re merging the push and shipit commands into a new command called “deploy”. We’re hoping this will clarify the use differences between “deploy” and “run."

**Comment by gregdek** [comment]
"The #379 issue is in Ryan and House's capable hands presently, Ryan with the run portion and House with the modules to support the shipit portion" --jag, 1 March

**Comment by gregdek** [comment]
Status: "mostly done, need to write docs"

**Comment by ryansb** [comment]
This is done - command reference for shipit is gone, all about deploy now. 

P.S. the push command still exists, but `deploy` runs push anyway so it's not part of the average user's deploy process.
