### ISSUE TITLE
Dockerfile -> Ansible Container conversion tool

### ISSUE THREAD

**Issue by gregdek** [ansible/ansible-container#380]
From jag email to Ansible Container list, 29 January 2017:

We’re working on a converter from a Dockerfile to an Ansible Container role and project. Initially, we’ll be falling back on Ansible’s “command” module to give you nudges toward using Ansible’s native modules for things like yum or apt or touch versus the command module, but in future releases we’re hoping to have the converter get smarter and make those translations for you.

**Comment by gregdek** [comment]
"The Dockerfile -> Ansible Container conversion tool is in decent working order." --jag, 1 March

**Comment by j00bar** [comment]
I'm considering this resolved and implemented.
