### ISSUE TITLE
Support vault password

### ISSUE THREAD

**Issue by splisson-altair** [ansible/ansible-container#381]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Add the capability to use Ansible vault by passing password file.

##### STEPS TO REPRODUCE
- Pass " "--vault-password-file ansible_vault_password.txt" at the end of the ansible-container command (options)
- Place the password file in ansible folder along with main.yml

Will send PR

**Comment by chouseknecht** [comment]
@splisson-altair, thank-you for your interest in Ansible Container, and for taking the time to open an issue.

You can use a vault file in `main.yml`, and pass the --vault-password-file option using `--` on the build command. For example:

```
$ ansible-container build -- --vault-password-file=/ansible-container/ansible/vault-password.txt
```

The base path of the project gets mounted into the build container as `/ansible-container`, so I believe the above will work.

Closing this, as I believe the above addresses the issue, but please reply back, if you have difficulty getting it to work.

Thanks!
