### ISSUE TITLE
ansible-container for docker-py v2.x

### ISSUE THREAD

**Issue by emeusel** [ansible/ansible-container#410]
Hi,

I'd like to create a branch of ansible-container, which uses docker-py v2.x. Do you know, if there is anything like that, already?

Thanks + Best regards
Erik

**Comment by j00bar** [comment]
Hi @emeusel -

Thanks for your interest in Ansible Container! Our release 0.9, due out this month, is a major refactor, and it uses docker-py 2.1 - you're welcome to check it out under the refactor/mk-ii branch.

HTH - thanks again!
