### ISSUE TITLE
Docker cli in orchestration container depends on, but doesn't include shared libs

### ISSUE THREAD

**Issue by gaieges** [ansible/ansible-container#44]
Getting the following exception when trying to gather facts in the first ansible play within the ''ansible_container'' orchestration container:

```
ansible-container_1  | Using /ansible-container/ansible/ansible.cfg as config file
ansible-container_1  | Loaded callback default of type stdout, v2.0
ansible-container_1  |
ansible-container_1  | PLAYBOOK: main.yml *************************************************************
ansible-container_1  | 2 plays in main.yml
ansible-container_1  |
ansible-container_1  | PLAY [host1] ********************************************************************
ansible-container_1  |
ansible-container_1  | TASK [setup] *******************************************************************
ansible-container_1  | /usr/bin/docker: error while loading shared libraries: libapparmor.so.1: cannot open shared object file: No such file or directory
ansible-container_1  | An exception occurred during task execution. The full traceback is:
ansible-container_1  | Traceback (most recent call last):
ansible-container_1  |   File "/src/ansible/lib/ansible/executor/task_executor.py", line 124, in run
ansible-container_1  |     res = self._execute()
ansible-container_1  |   File "/src/ansible/lib/ansible/executor/task_executor.py", line 411, in _execute
ansible-container_1  |     self._connection = self._get_connection(variables=variables, templar=templar)
ansible-container_1  |   File "/src/ansible/lib/ansible/executor/task_executor.py", line 636, in _get_connection
ansible-container_1  |     connection = self._shared_loader_obj.connection_loader.get(conn_type, self._play_context, self._new_stdin)
ansible-container_1  |   File "/src/ansible/lib/ansible/plugins/__init__.py", line 349, in get
ansible-container_1  |     obj = obj(*args, **kwargs)
ansible-container_1  |   File "/src/ansible/lib/ansible/plugins/connection/docker.py", line 77, in __init__
ansible-container_1  |     docker_version = self._get_docker_version()
ansible-container_1  |   File "/src/ansible/lib/ansible/plugins/connection/docker.py", line 116, in _get_docker_version
ansible-container_1  |     cmd_output = subprocess.check_output(cmd)
ansible-container_1  |   File "/usr/local/lib/python2.7/subprocess.py", line 573, in check_output
ansible-container_1  |     raise CalledProcessError(retcode, cmd, output=output)
ansible-container_1  | CalledProcessError: Command '['/usr/bin/docker', 'version']' returned non-zero exit status 127
ansible-container_1  |
ansible-container_1  | fatal: [host1]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}
ansible-container_1  |
```

Seems like it's breaking on attempts to begin connection to remote docker container, as those libs are not part of the container itself, per the included volumes in the template. 

This is all being run from a clean xenial64 host.

**Comment by gaieges** [comment]
Get the same issue on trusty64

**Comment by gaieges** [comment]
Were you able to confirm that this change worked?

That seems to have helped the apparmor issue, but am still getting this with the stock raw commands in the 'all' play (even in the ''test'' dir you guys provided):

```
ansible-container_1  | TASK [raw] *********************************************************************
ansible-container_1  | Cannot connect to the Docker daemon. Is the docker daemon running on this host?
ansible-container_1  | Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

I tried the same thing with the docker engine in the container running, but get the same exception.  

It seems like the hosts are coming through properly and the resolution of the host->ip works as intended, just that the guest docker doesn't communicate with the host docker.

**Comment by chouseknecht** [comment]
Do you have the following environment vars set on the host:

DOCKER_HOST=tcp://<IP_address of the host>:2376
DOCKER_TLS_VERIFY=1 (Leave undefined, if server name should not be verified.)
DOCKER_CERT_PATH=/certficate/dir

for example:

```
export DOCKER_TLS_VERIFY=1
export DOCKER_HOST=tcp://10.0.2.15:2376
export DOCKER_CERT_PATH=~/.docker
```

At a minimum DOCKER_HOST should be set to a URI that includes the IP of the host. A Unix socket won't work.

DOCKER_CERT_PATH may not be required (haven't tested this yet). I'm running with it defined and a secured Docker daemon. If you're daemon is secure, definitely define it. The directory path provided will be used in a bind volume, giving the build container's docker client access to the client cert and key.

Hope this helps.

**Comment by gaieges** [comment]
Ahh.. The DOCKER_HOST portion seems to have helped, thanks!  Not working with a secured host at the moment (just trying to get this working), but good to know for the future.

Didn't see that noted anywhere in the docs though, did I miss it?

**Comment by gaieges** [comment]
Saw your updates to the doc, thanks for that!  Much appreciated.
