### ISSUE TITLE
init throws AnsibleContainerAlreadyInitializedException in virtualenv when trying to init from role on Ansible Galaxy

### ISSUE THREAD

**Issue by wbrefvem** [ansible/ansible-container#463]
##### ISSUE TYPE

 - Bug Report

##### container.yml 

n/a

##### main.yml 

n/a

##### OS / ENVIRONMENT

Fedora 25
```
Ansible Container, version 0.9.0.0
Linux, unknownE4B318893A0F, 4.10.11-200.fc25.x86_64, #1 SMP Tue Apr 18 17:25:01 UTC 2017, x86_64
2.7.13 (default, Jan 12 2017, 17:59:37) 
[GCC 6.3.1 20161221 (Red Hat 6.3.1-1)] /usr/bin/python
```
OS X
```
Ansible Container, version 0.9.0.0
Darwin, calliope.local, 16.5.0, Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64, x86_64
2.7.10 (default, Feb  6 2017, 23:53:20) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] ./ansible-container/.venv/bin/python
```
virtualenv
```
(.venv) [user@host ansible-container] % virtualenv --version
15.1.0
```
##### SUMMARY

Getting Started docs recommend running ```ansible-container init ansible.django-template```. Leaving aside the issue that this role is no longer available on Galaxy, running it in a venv raises ```AnsibleContainerAlreadyInitializedException```. Same if you substitute existing roles ```ansible.django-template``` or ```ansible.nginx-container```. Results the same using Python 3.4.2, 3.6.1 and Fedora 25 with Python 2.7.13. Bug disappears if running ```ansible-container``` globally.
##### STEPS TO REPRODUCE

Assumes Docker, virtualenv installed
```
mkdir foo
cd foo
[virtualenv .venv | virtualen .venv -p python3]
source .venv/bin/activate
pip install ansible-container[docker]
ansible-container init ansible.django-gulp-nginx
```

##### EXPECTED RESULTS

```ansible-container``` should install `ansible.django-gulp-nginx` from Ansible Galaxy in `./foo`, or if the role is not found on AG, it should print an error message saying so. In other words, behavior of venv installation should be the same as behavior of global installation.

##### ACTUAL RESULTS

```
(.venv) [user@host ansible-container] % ansible-container --debug init ansible.django-gulp-nginx
2017-04-28T13:25:55.679769 Ansible Container is already initialized [container.cli] caller_file=./ansible-container/.venv/lib/python2.7/site-packages/container/cli.py caller_func=__call__ caller_line=261
```

```
(.venv) [user@host ansible-container] % docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

```
(.venv) [user@host ansible-container] % ls -al
total 0
drwxr-xr-x    3   user  group     102 Apr 28 13:13 .
drwxr-xr-x  108 user  group  3672 Apr 28 13:13 ..
drwxr-xr-x    7   user  group    238 Apr 28 13:13 .venv
```

**Comment by wbrefvem** [comment]
My best guess is that [this](https://github.com/ansible/ansible-container/blob/develop/container/core.py#L106) is where the exception is thrown, since this is the only place where the exception is raised with the default error message. This would mean that the path construction is to blame, either the base path or the behavior of ```os.path``` under a venv. If I can find a fix, I'll submit a PR.

**Comment by chouseknecht** [comment]
Based on the *steps to reproduce*, the issue appears to be that you're creating the `.venv` directory inside the project directory. The `init` command expects to find an empty directory, but instead finds the existence of `.venv`

I don't know that we want to change this behavior, as the `init` command may drop many different files into the directory, potentially overwriting whats there. Because of this, it's not reasonable to only check for the existence of `container.yml`.

**Comment by chouseknecht** [comment]
As you point out, the example role `ansible.django-template` is missing from Galaxy. I pinged @j00bar, and we'll get that sorted out shortly.

Thanks for taking the time to try Ansible Container, and for bringing this to our attention!

**Comment by wbrefvem** [comment]
Ah, that makes sense. I'll work on `--force`. 

I think it also makes sense to preserve specific error messages  when `cli.HostCommand.__call__` catches them. For example, in this case I would have got `The init command can only be run in an empty directory` instead of the less descriptive (and not true) `Ansible Container already initialized`. Or maybe a new, more specific exception makes more sense.
