### ISSUE TITLE
More specific error messaging for init 

### ISSUE THREAD

**Issue by wbrefvem** [ansible/ansible-container#474]
##### ISSUE TYPE

 - Feature Idea

##### container.yml 

n/a

##### main.yml 

n/a

##### OS / ENVIRONMENT

```
Linux, localhost.localdomain, 4.10.12-200.fc25.x86_64, #1 SMP Sat Apr 22 03:03:34 UTC 2017, x86_64
3.5.3 (default, Apr 24 2017, 13:32:13) 
[GCC 6.3.1 20161221 (Red Hat 6.3.1-1)] ./ansible-container/.venv/bin/python3
ERROR	No Ansible Container project data found - do you need to run "ansible-container init"?	
```

##### SUMMARY

Currently, `container.cli.HostCommand.__call__` clobbers the specific error messages that get passed to `AnsibleContainerAlreadyInitializedException` in `container.core` with a generic message. I would like to capture and pass on the raised message to provide better error reporting, which is what happens [here](https://github.com/ansible/ansible-container/blob/develop/container/cli.py#L268).

##### STEPS TO REPRODUCE

For example, if I try to run `init` in a non-empty directory, currently I get:

```
(.venv) [user@localhost non-empty-dir]$ ls -a
.  ..  theres-a-file-here  .venv
(.venv) [user@localhost non-empty-dir]$ ansible-container init ansible.django-template
ERROR	Ansible Container is already initialized	
(.venv) [user@localhost non-empty-dir]$
```
This is what I'm proposing, which is more informative:
```
(.venv) [user@localhost non-empty-dir]$ ansible-container init ansible.django-template
ERROR	The init command can only be run in an empty directory.	
(.venv) [user@localhost non-empty-dir]$
```

**Comment by j00bar** [comment]
+1 that this can be better. We didn't make this transition terribly well from <0.9, where there was an `ansible/` directory.
