### ISSUE TITLE
Errors on Fedora 24

### ISSUE THREAD

**Issue by dustymabe** [ansible/ansible-container#6]
I can't seem to get this up and working on F24 (beta right now) - perhaps an install guide might help but for now I was following some of the steps from the Dockerfile in #4. Either way here are the errors I am seeing:

```
[root@f24 ansible-container (master=)]# git log | head -n 1
commit ebdc723c0e8866472c6aade2c2d313a440a5582a
[root@f24 ansible-container (master=)]# cd test-v1/
[root@f24 test-v1 (master=)]# ansible-container --debug build --no-flatten
Ansible Container image has ID sha256:08b6b60b643bc1be5bc7114d7ed7b684c14eb2c09a6bf6111fb72a17ef28b809
Using temporary directory /tmp/tmpkb98_c...
Starting Compose engine to build your images...
Using temporary directory /tmp/tmpyQnzYZ...
The DOCKER_CERT_PATH variable is not set. Defaulting to a blank string.

ERROR: for ansible-container  create .: volume name invalid: "." includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed
Attaching to 
Cleaning up temporary directory /tmp/tmpyQnzYZ...
The DOCKER_CERT_PATH variable is not set. Defaulting to a blank string.

ERROR: for ansible-container  create .: volume name invalid: "." includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed
Attaching to ansible_host2_1, ansible_host1_1
```

This then waits forever and I have to CTRL-C:

```
^CGracefully stopping... (press Ctrl+C again to force)
Stopping ansible_host1_1 ... 
Stopping ansible_host1_1 ... done
Stopping ansible_host2_1 ... done
Cleaning up temporary directory /tmp/tmpkb98_c...
need more than 0 values to unpack
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible_container-0.1-py2.7.egg/container/cli.py", line 126, in commandline
    **vars(args))
  File "/usr/lib/python2.7/site-packages/ansible_container-0.1-py2.7.egg/container/engine.py", line 108, in cmdrun_build
    limit=1, all=True
ValueError: need more than 0 values to unpack
```

**Comment by dustymabe** [comment]
The version of docker on my system right now is: `docker-1.10.3-10.git8ecd47f.fc24.x86_64`

**Comment by pyro2927** [comment]
Seeing the same thing on commit af27b9f1c3c852ba54c3443e9e91979e34f7a813. OS: OS X 10.11.5, `Docker version 1.11.1, build 5604cbe`.

**Comment by pyro2927** [comment]
This appears to be an an issue when you don't have a `DOCKER_CERT_PATH` set in your ENV.  The [template](https://github.com/ansible/ansible-container/blob/dfeda5dac1c5b9db491b6b27f9e73469ecd036df/container/templates/build-docker-compose.j2.yml#L16) then tries to use an empty string for a mount point.

**Comment by jctanner** [comment]
Workaround is to comment out the DOCKER_CERT_PATH volume in the template.

**Comment by gaieges** [comment]
Commenting out ```DOCKER_CERT_PATH``` in the template seems to have helped me as well.  Setting the env variable on the shell doesn't.

I still get the exception but it continues on to run the ansible portion at least.

**Comment by chouseknecht** [comment]
Official install and docker config instructions now live [at the official doc site](http://docs.ansible.com/ansible-container/). The source is in https://github.com/ansible/ansible-container/tree/master/docs.

**Comment by j00bar** [comment]
Thanks, @chouseknecht, for documenting configuration when not using Docker Machine. Please reopen this issue if you feel the docs do not sufficiently resolve it.
