### ISSUE TITLE
Can't use --roles-path outside build

### ISSUE THREAD

**Issue by rubencabrera** [ansible/ansible-container#607]
##### ISSUE TYPE
 - Bug Report

##### container.yml 

```
version: "2"
settings:
  conductor_base: ubuntu:xenial
  project_name: odoo

services: 
  frontend:
    from: "ubuntu:xenial"
    ports:
      - "8080:80"
    command: [nginx]
    roles:
      - basicos
      - nginx 

  database:
    from: "ubuntu:xenial"
    expose:
      - 5432
    roles:
      - basicos
      - postgresql
      - ansible-postgresql-objects
      
registries: {}
```

##### OS / ENVIRONMENT

```
Ansible Container, version 0.9.2rc0
Linux, hprojo, 4.4.0-79-generic, #100-Ubuntu SMP Wed May 17 19:58:14 UTC 2017, x86_64
2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] /home/ruben/.virtualenvs/ansible-container/bin/python
{
  "ContainersPaused": 0, 
  "Labels": null, 
  "CgroupDriver": "cgroupfs", 
  "ContainersRunning": 0, 
  "ContainerdCommit": {
    "Expected": "9048e5e50717ea4497b757314bad98ea3763c145", 
    "ID": "9048e5e50717ea4497b757314bad98ea3763c145"
  }, 
  "InitBinary": "docker-init", 
  "NGoroutines": 23, 
  "Swarm": {
    "ControlAvailable": false, 
    "NodeID": "", 
    "Error": "", 
    "RemoteManagers": null, 
    "LocalNodeState": "inactive", 
    "NodeAddr": ""
  }, 
  "LoggingDriver": "json-file", 
  "OSType": "linux", 
  "HttpProxy": "", 
  "Runtimes": {
    "runc": {
      "path": "docker-runc"
    }
  }, 
  "DriverStatus": [
    [
      "Root Dir", 
      "/var/lib/docker/aufs"
    ], 
    [
      "Backing Filesystem", 
      "extfs"
    ], 
    [
      "Dirs", 
      "44"
    ], 
    [
      "Dirperm1 Supported", 
      "true"
    ]
  ], 
  "OperatingSystem": "Ubuntu 16.04.2 LTS", 
  "Containers": 2, 
  "HttpsProxy": "", 
  "BridgeNfIp6tables": true, 
  "MemTotal": 7247073280, 
  "SecurityOptions": [
    "name=apparmor", 
    "name=seccomp,profile=default"
  ], 
  "Driver": "aufs", 
  "IndexServerAddress": "https://index.docker.io/v1/", 
  "ClusterStore": "", 
  "InitCommit": {
    "Expected": "949e6fa", 
    "ID": "949e6fa"
  }, 
  "Isolation": "", 
  "SystemStatus": null, 
  "OomKillDisable": true, 
  "ClusterAdvertise": "", 
  "SystemTime": "2017-06-15T16:02:05.177282769+02:00", 
  "Name": "hprojo", 
  "CPUSet": true, 
  "RegistryConfig": {
    "InsecureRegistryCIDRs": [
      "127.0.0.0/8"
    ], 
    "IndexConfigs": {
      "docker.io": {
        "Official": true, 
        "Name": "docker.io", 
        "Secure": true, 
        "Mirrors": []
      }
    }, 
    "Mirrors": []
  }, 
  "DefaultRuntime": "runc", 
  "ContainersStopped": 2, 
  "NCPU": 4, 
  "NFd": 16, 
  "Architecture": "x86_64", 
  "KernelMemory": true, 
  "CpuCfsQuota": true, 
  "Debug": false, 
  "ID": "CIPE:BTRA:KTA3:V263:TSMS:YNGA:EIVX:CK4A:MZAP:R4SU:Q2JJ:EWUE", 
  "IPv4Forwarding": true, 
  "KernelVersion": "4.4.0-79-generic", 
  "BridgeNfIptables": true, 
  "NoProxy": "", 
  "LiveRestoreEnabled": false, 
  "ServerVersion": "17.05.0-ce", 
  "CpuCfsPeriod": true, 
  "ExperimentalBuild": false, 
  "MemoryLimit": true, 
  "SwapLimit": false, 
  "Plugins": {
    "Volume": [
      "local"
    ], 
    "Network": [
      "bridge", 
      "host", 
      "macvlan", 
      "null", 
      "overlay"
    ], 
    "Authorization": []
  }, 
  "Images": 22, 
  "DockerRootDir": "/var/lib/docker", 
  "NEventsListener": 0, 
  "CPUShares": true, 
  "RuncCommit": {
    "Expected": "9c2d8d184e5da67c95d601382adf14862e4f2228", 
    "ID": "9c2d8d184e5da67c95d601382adf14862e4f2228"
  }
}
{
  "KernelVersion": "4.4.0-79-generic", 
  "Arch": "amd64", 
  "BuildTime": "2017-05-04T22:10:54.638119411+00:00", 
  "ApiVersion": "1.29", 
  "Version": "17.05.0-ce", 
  "MinAPIVersion": "1.12", 
  "GitCommit": "89658be", 
  "Os": "linux", 
  "GoVersion": "go1.7.5"
}
```
##### SUMMARY
Can' use the --roles-path flag to specify a local path where roles can be found. 

##### STEPS TO REPRODUCE
After a build using the --roles-path, use the same flag with run or install commands:

```
ansible-container run --roles-path /home/myuser/roles-dir
ansible-container install roleName --roles-path /home/myuser/roles-dir
```

##### EXPECTED RESULTS

Get the containers running with the roles in the desired folder.
or
Get the role roleName in the specified folder installed in the current project (I don't know if this is a bug or a feature request, because I didn't find examples of this in the docs, as I did for **run**, **push** and **shipit**).

##### ACTUAL RESULTS
```
usage: ansible-container [-h] [--debug] [--devel] [--engine ENGINE_NAME]
                         [--project-path BASE_PATH]
                         [--project-name PROJECT_NAME] [--var-file VAR_FILE]
                         [--no-selinux]
                         {run,help,deploy,stop,destroy,restart,init,version,build,install,push,import}
                         ...
ansible-container: error: unrecognized arguments: --roles-path /home/myuser/roles-dir
```

**Comment by chouseknecht** [comment]
@rubencabrera 

Thanks for using Ansible Container, and for sharing your feedback. 

The `--roles-path` option is intended to make roles available to the conductor container during `build`. What's the use case for needing to access roles during `run` and `install`? 

The generated playbook for `run` will not know to execute your roles, and the `install` command does not execute a playbook. The only think I can think of is that there maybe a bug, or maybe there's a case to be made, for accessing the variables introduced by a role.

**Comment by rubencabrera** [comment]
The reason I am trying to use --roles-path is because I can't run nor install roles that were in the specified folder at build time. I get the following error:
```
ansible.errors.AnsibleError: the role 'myRoleName' was not found in ./roles:/src/roles:/etc/ansible/roles:.
```
It is also mentioned[ in the documentation for accessing roles](https://github.com/ansible/ansible-container/blame/develop/docs/rst/roles/access.rst#L39).

My workaround was to copy all the needed roles to the roles folder in the project.

**Comment by j00bar** [comment]
Hi @rubencabrera -

The `ansible-container install` command is meant to validate the role reference you gave and ultimately alter your `requirements.yml` file to include the role and its dependencies. Then, during build, the Conductor container's build includes a run of `ansible-galaxy install -r your-requirements.yml` to grab the roles from Galaxy and burn them into the Conductor container image.

The `--roles-path` argument during build is meant to reference roles that are already on your host but not in your project path, mounting that volume into the Conductor container for use by Ansible.

Does that clarify the intent behind the two different modes of operation? Any suggestions about how we can clarify that distinction in the documentation better?

Thanks!

**Comment by flaub** [comment]
See #620 for a case where the `--roles-path` option needs to be available outside the `build` command.

**Comment by chouseknecht** [comment]
@rubencabrera 

You can now use `--roles-path` with the `build`, `run`, `deploy`, `push`, `start`, `stop`, `restart`, and `destroy` commands.  And as @j00bar explained, it's not intended to work with `install`.

Closing this issue, as I think we have addressed all the issues. If not, please feel free to comment, and we will reopen it. 

Thanks again for sharing your feedback, and helping the project. 

Thanks!

--Chris
