### ISSUE TITLE
ansible-container vs. docker_container, docker_image and docker_service modules

### ISSUE THREAD

**Issue by lewer** [ansible/ansible-container#619]
Hello,

Until now, I have used docker_container, docker_image and docker_service to manage my Docker containers. I have a single Docker server which runs all my containers, no Kubernetes nor OpenShift. Would ansible-container bring something new ? 

Thanks.

**Comment by chouseknecht** [comment]
Ansible Container replaces Dockerfile with Ansible roles. You can literally build images without a Dockerfile.

It also manages a multi-container application, as opposed to the Ansible modules, which focus on managing a single container or single image. So if you're attempting to manage a complex application, Ansible Container would consolidate the configuration, giving you a single orchestration document (i.e.,`container.yml`). And with a `container.yml`, it would be clear which services are part of the application, how they're built, and how they're connected.

The other thing Ansible Container does is provide a workflow. Within `container.yml` you can declare settings that are specific to your development environment. For example, in development you may want to expose different ports, mount a local directory, run a service (e.g. a node service to compile Javascript assets) not part of production, etc. This is all done using the `dev_overrides` directive for a service.

When you execute `ansible-container run` the application will launch with the development settings. From your CI/CD environment, execute `ansible-container run --prodcution` to start the app with production settings, and execute tests. And finally, when it's time to deploy to production, use `ansible-container deploy` to push images to your production registry, and update the production containers.

The `run` and `deploy` tasks are carried out via generated Ansible playbooks. So if you're deploying to Docker, you would use the default engine (Docker), and the deployment playbook would run the `docker_service` module to update the containers on your production host.

When you decide one day to move to a container platform, you won't have to throw away your `container.yml`. You'll be able to start using it as is, and as you learn more about the platform, you can add platform specific settings to each service, and tweak the deployment. Of course, at the moment, the only supported platforms other than Docker are K8s and OpenShift. But as the project matures, I'm confident additional engines will be supported.  

Hope that helps. Please follow up with any additional questions.

**Comment by chouseknecht** [comment]
@lewer Thanks for the question! Closing, since there has not been any follow up discussion. Feel free to continue commenting here, or drop us a line on [the mailing list](https://groups.google.com/forum/#!forum/ansible-container).

**Comment by manuel-mauky** [comment]
Hi @chouseknecht,
I'm in a similar situation and your comment helps me a lot. However, I don't fully understand the following paragraph:

>The run and deploy tasks are carried out via generated Ansible playbooks. So if you're deploying to Docker, you would use the default engine (Docker), and the deployment playbook would run the docker_service module to update the containers on your production host.

I don't get what I have to do so that `ansible-container deploy` run's `docker_service` the way you've described it here. 
Can you point me to a more detailed description of this use-case?

Thanks.

**Comment by etnbrd** [comment]
I think he meant that the `ansible-container deploy` command uses the `docker_service` ansible module under the hood, if you use Docker as your container engine.
So you wouldn't have to do anything.
