### ISSUE TITLE
Be able to use ansible-container build without an /ansible folder

### ISSUE THREAD

**Issue by cdrage** [ansible/ansible-container#64]
I'd like to either specify the folder to build (ex. `ansible-container build -f ./test` or even `ansible-container build test/ansible`).

Another thing is that I'm forced to use a folder named `ansible`. `ansible-container` should detect whether there is a container.yml in the folder and run it appropriately without the need of having an `ansible` container.

**Comment by j00bar** [comment]
Reasonable requests. Thanks!

**Comment by danvaida** [comment]
+1
If we could pass either a `-f` (as in file) or `-p` (as in path), would be great. Would it make sense to have the same for `ansible-container run`?
