### ISSUE TITLE
Ansible Container Errors in Vagrant VM

### ISSUE THREAD

**Issue by aric49** [ansible/ansible-container#669]
##### ISSUE TYPE

 - Bug Report

##### container.yml 

Occurs on fresh `ansible-container init`

##### OS / ENVIRONMENT

```
Ansible Container, version 0.9.1
Linux, node01, 4.4.0-78-generic, #99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017, x86_64
2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] /usr/bin/python

```
##### SUMMARY

Upon initializing a new project in a Vagrant VM and trying to install a role, I often get the error: `ERROR Conductor container can't be found. Run ansible-container build first.`  I am also experiencing some other odd behavior when running the ansible-container build in a Vagrant VM, as seen in the "Steps to Reproduce" section.

##### STEPS TO REPRODUCE

The Vagrantfile I am using to create this environment is located in the following repo:
https://github.com/aric49/ansible_container_lab

Just run `vagrant up`

Then:

```
ubuntu@node01:~$ mkdir project
ubuntu@node01:~$ cd project/
ubuntu@node01:~/project$ ls
ubuntu@node01:~/project$
ubuntu@node01:~/project$ ansible-container init
Ansible Container initialized.
ubuntu@node01:~/project$
ubuntu@node01:~/project$
ubuntu@node01:~/project$
ubuntu@node01:~/project$ ansible-container install chouseknecht.mariadb-container
ERROR   Conductor container can't be found. Run `ansible-container build` first
```

If I try running build, then the install again, I get the following:

```
ubuntu@node01:~/project$ ansible-container build
Building Docker Engine context...	
Starting Docker build of Ansible Container Conductor image (please be patient)...	
Parsing conductor CLI args.
Docker™ daemon integration engine loaded. Build starting.	project=project
All images successfully built.
Conductor terminated. Cleaning up.	command_rc=0 conductor_id=048d3e63e0106f6e03c13822729d3e6219a6812cc7440623756aa676d8b47936 save_container=False
ubuntu@node01:~/project$ 
ubuntu@node01:~/project$ 
ubuntu@node01:~/project$ 
ubuntu@node01:~/project$ ansible-container install chouseknecht.mariadb-container
Parsing conductor CLI args.
- downloading role 'mariadb-container', owned by chouseknecht
- downloading role from https://github.com/chouseknecht/mariadb-container/archive/master.tar.gz
- extracting chouseknecht.mariadb-container to /tmp/tmpCnxsSk/chouseknecht.mariadb-container
- chouseknecht.mariadb-container (master) was installed successfully
Conductor terminated. Cleaning up.	command_rc=0 conductor_id=55b454681781990a372c8e2ea4aac743bc2404248c80dc75cfda135127c2cd33 save_container=False
ubuntu@node01:~/project$ 
```

Seems to have worked.   Let's try running `build` again:

```
ubuntu@node01:~/project$ ansible-container build
Building Docker Engine context...	
Starting Docker build of Ansible Container Conductor image (please be patient)...	
Parsing conductor CLI args.
Docker™ daemon integration engine loaded. Build starting.	project=project
Building service...	project=project service=chouseknecht.mariadb-container
Traceback (most recent call last):
  File "/usr/bin/conductor", line 11, in <module>
    load_entry_point('ansible-container', 'console_scripts', 'conductor')()
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/cli.py", line 360, in conductor_commandline
    **params)
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/core.py", line 619, in conductorcmd_build
    cur_image_id = engine.get_image_id_by_tag(service['from'])
KeyError: 'from'
Conductor terminated. Cleaning up.	command_rc=1 conductor_id=55bd0ea90e6ece6f8705f5432260e966ae534cb025449552f5fb60fad9ad6a2f save_container=False
ERROR	Conductor exited with status 1	
```

##### EXPECTED RESULTS

I expected that I could install a role without having to build the project prior.   I would also expect the build to complete after installing a basic container role.

##### ACTUAL RESULTS

I receive an error upon initially installing the container role telling me I have to build the project first.  After building, the role then cannot be built after installing. 

Any help ya'll can give is super appreciated.  Thanks in advance for checking into this!

**Comment by chouseknecht** [comment]
@aric49 

It's true that the `install` command requires a conductor container. This is because we only install Ansible within the conductor, and we only run `ansible-galaxy` inside the conductor. 

The second run of `build` is hitting a bug in the `chouseknecht.mariadb-container` role. That role is needs to be upgraded to version 0.9+ of Ansible Container. Specifically it should have a `from` directive in `meta/container.yml`.

**Comment by aric49** [comment]
Thanks for the response.   Just for clarification, as of version 0.9, an initial `ansible-container build` has to be executed prior to installing a role?

Also, would you recommend a role that is version 0.9 compatible I can use for some lab examples I am working on?  I have tried browsing Ansible Galaxy, but I don't really see a way to browse only "container" roles.

**Comment by chouseknecht** [comment]
@aric49 

Take look at [ansible/ansible-container-demo](https://github.com/ansible/ansible-container-demo). That should help. It uses a `container app` role to init the product, and it relies on a `container enabled` role to supply the nginx service. 

To view different role types in Galaxy, got to the Browse Roles page, and set the search box drop-down to `role types`. This will allow you to choose `container enabled` or `container app`.

![galaxy](https://user-images.githubusercontent.com/1282865/28728226-d18efe18-7395-11e7-9558-7d8183deb311.png)

**Comment by chouseknecht** [comment]
@aric49 

Installing the role requires a conductor container, so yes, you must first build the project.

We actually don't install the role using `ansible-galaxy`. We install it via some code that imports [ansible.galaxy bits here](https://github.com/ansible/ansible-container/blob/develop/container/utils/galaxy.py).

**Comment by j00bar** [comment]
@chouseknecht It's conceivable that after the prebaked branch merges, we can modify install to use the base conductor image versus the built conductor image for an install.

**Comment by chouseknecht** [comment]
@j00bar 

Running into another bug with container enabled roles. The install process adds the role to the conductor container (not the image). I think it places it in `/etc/roles`. Next run `build`, and get the following:

```
/usr/lib/python2.7/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.22) or chardet (2.2.1) doesn't match a supported version!
  RequestsDependencyWarning)
Parsing conductor CLI args.
2017-07-28T19:16:45.031729 Processing defaults section... [container.config] caller_file=/_ansible/container/config.py caller_func=_process_defaults caller_line=320
2017-07-28T19:16:45.040944 Processing section...          [container.config] caller_file=/_ansible/container/config.py caller_func=_process_top_level_sections caller_line=329 section=volumes
2017-07-28T19:16:45.052682 Processing section...          [container.config] caller_file=/_ansible/container/config.py caller_func=_process_top_level_sections caller_line=329 section=registries
2017-07-28T19:16:45.065792 Processing section...          [container.config] caller_file=/_ansible/container/config.py caller_func=_process_top_level_sections caller_line=329 section=secrets
2017-07-28T19:16:45.075195 Processing service...          [container.config] caller_file=/_ansible/container/config.py caller_func=_process_services caller_line=335 service=u'mariadb' service_data={u'roles': [u'chouseknecht.mariadb-container']}
Traceback (most recent call last):
  File "/usr/bin/conductor", line 11, in <module>
    load_entry_point('ansible-container', 'console_scripts', 'conductor')()
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/cli.py", line 382, in conductor_commandline
    conductor_config = AnsibleContainerConductorConfig(list_to_ordereddict(containers_config))
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/config.py", line 292, in __init__
    self._process_services()
  File "/_ansible/container/config.py", line 352, in _process_services
    role_metadata = get_metadata_from_role(role_name)
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/utils/__init__.py", line 271, in get_metadata_from_role
    return get_content_from_role(role_name, os.path.join('meta', 'container.yml'))
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/utils/__init__.py", line 260, in get_content_from_role
    role_path = resolve_role_to_path(role_name)
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/utils/__init__.py", line 209, in resolve_role_to_path
    loader=loader)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/role/include.py", line 59, in load
    return ri.load_data(data, variable_manager=variable_manager, loader=loader)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/base.py", line 242, in load_data
    ds = self.preprocess_data(ds)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/role/definition.py", line 94, in preprocess_data
    (role_name, role_path) = self._load_role_path(role_name)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/role/definition.py", line 187, in _load_role_path
    raise AnsibleError("the role '%s' was not found in %s" % (role_name, ":".join(role_search_paths)), obj=self._ds)
ansible.errors.AnsibleError: the role 'chouseknecht.mariadb-container' was not found in ./roles:/src/roles:/etc/ansible/roles:.
```
The process of attempting to assemble together all the default vars from roles raises the above error. It cannot find a local copy of the newly intalled role. It *seems* like the role should get installed in the local roles directory, or `/src/roles` from within the conductor. **Is there any reason to not do that?**

**Comment by chouseknecht** [comment]
@j00bar 

And one more fun thingy... 

Installing the role creates a service name of 'chouseknecht.mariadb-container`. That sucks. There should be a way to override this. Probably something in the role's meta data.

**Comment by aric49** [comment]
Awesome! Thank you so much. This has cleared up a lot.    Based on the container docs, I was under the impression that roles could be installed without first building the project. 

I think it would be helpful if some language was added to the docs to clear up some of these things.

Also, I ran into the same error as well that @chouseknecht is seeing with:

```
 raise AnsibleError("the role '%s' was not found in %s" % (role_name, ":".join(role_search_paths)), obj=self._ds)
ansible.errors.AnsibleError: the role 'chouseknecht.mariadb-container' was not found in ./roles:/src/roles:/etc/ansible/roles:.
```

**Comment by aric49** [comment]
Great advice @chouseknecht and @j00bar! It seems the issue is with the roles and not directly with Ansible Container itself.. Closing this issue.
