### ISSUE TITLE
Update README.md examples

### ISSUE THREAD

**Issue by imphil** [ansible/ansible-container#682]
##### ISSUE TYPE
 - Documentation Report

##### SUMMARY
The README.md seems to be (partially) outdated. For example, it references to the `shipit` command, which was renamed to `deploy`. It could well be that there are other outdated examples in there as well, maybe someone with an up-to-date view on the current way of doing things could have a look?

**Comment by chouseknecht** [comment]
@imphil 

Thanks for pointing this out!  Fixed up the README. Please let us know, if you see anything else that needs some luv.
