### ISSUE TITLE
Missing files under container/docker/files/

### ISSUE THREAD

**Issue by shalomb** [ansible/ansible-container#692]
##### ISSUE TYPE

 - Bug Report

##### container.yml 

```
# vanilla container.yml 
$ mkdir /tmp/foo; cd /tmp/foo;
$ ansible-container init
```

##### OS / ENVIRONMENT

Attempting to validate https://github.com/ansible/ansible-container/issues/566

Running `ansible-container` from source (`develop/HEAD`) following instructions from http://docs.ansible.com/ansible-container/installation.html#running-from-source

```
$$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04 LTS
Release:        16.04
Codename:       xenial

$ ansible-container version
Ansible Container, version 0.9.2rc0  
```
##### SUMMARY

`ansible-container` throws an exception on a missing file at `/usr/local/lib/python2.7/dist-packages/container/docker/files/setup.py`

##### STEPS TO REPRODUCE

```
$ ansible-container build
Building Docker Engine context...
ERROR   Unknown exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/container/cli.py", line 291, in __call__
    getattr(core, u'hostcmd_{}'.format(args.subcommand))(**vars(args))
  File "/usr/local/lib/python2.7/dist-packages/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/container/core.py", line 160, in hostcmd_build
    environment=env_vars
  File "/usr/local/lib/python2.7/dist-packages/container/docker/engine.py", line 87, in __wrapped__
    return fn(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/container/docker/engine.py", line 871, in build_conductor_image
    arcname='container-src/conductor-build/setup.py')
  File "/usr/lib/python2.7/tarfile.py", line 2007, in add
    tarinfo = self.gettarinfo(name, arcname)
  File "/usr/lib/python2.7/tarfile.py", line 1879, in gettarinfo
    statres = os.lstat(name)
OSError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/container/docker/files/setup.py'
```

The following files are also missing

```
/usr/local/lib/python2.7/dist-packages/container/docker/files/conductor-requirements.yml
/usr/local/lib/python2.7/dist-packages/container/docker/files/conductor-requirements.txt
```

##### EXPECTED RESULTS

`ansible-container` should attempt to start building the container.

##### ACTUAL RESULTS

```

```

**Comment by chouseknecht** [comment]
@shalomb 

Thank you for using Ansible Container!  We appreciate you taking the time to share your feedback. 

I'll attempt to reproduce and sort this out.

**Comment by shalomb** [comment]
@chouseknecht I tried to do a little investigation to figure out why these files are missing but I've not had much luck.

For now, I've been able to workaround this issue by copying the files over

```
~/ansible-container$ git branch
* develop

~/ansible-container$ sudo cp setup.py conductor-requirements.{txt,yml} /usr/local/lib/python2.7/dist-packages/container/docker/files/
```

**Comment by wp-davisona** [comment]
Did you forget the `-e` in the pip install command?
http://docs.ansible.com/ansible-container/installation.html#running-from-source

`pip install -e .[docker,openshift]`

I was getting this exact error too (and your workaround worked), but when trying to investigate why it was happening I noticed how setup.py handles those files and that I couldn't reproduce it with the `-e` flag present.
https://packaging.python.org/tutorials/distributing-packages/#working-in-development-mode

**Comment by shalomb** [comment]
@wp-davisona .. hmm, it very well could have been that I missed `-e`. I remember I copied the commands out of http://docs.ansible.com/ansible-container/installation.html#running-from-source but must have missed this flag while debugging. And indeed I can't seem to reproduce now with `-e` present.

I guess we can close this issue.
