### ISSUE TITLE
ImportError: You must install Ansible Container with Docker(tm) support.

### ISSUE THREAD

**Issue by shalomb** [ansible/ansible-container#693]
##### ISSUE TYPE

 - Bug Report

##### container.yml 

```

```

##### OS / ENVIRONMENT

Same as on https://github.com/ansible/ansible-container/issues/692
##### STEPS TO REPRODUCE

Unsure about repro steps - this could be bespoke to my environment (but I fail to see how as it's a vanilla Ubuntu 16.04 machine with `ansible-container` built from source).

After about 5 or so minutes after invoking `ansible-container` build, it bombs out with this exception

```
$ ansible-container build
Building Docker Engine context...
Starting Docker build of Ansible Container Conductor image (please be patient)...
Parsing conductor CLI args.
Traceback (most recent call last):
  File "/usr/local/bin/conductor", line 11, in <module>
    load_entry_point('ansible-container==0.9.1', 'console_scripts', 'conductor')()
  File "/usr/local/lib/python2.7/dist-packages/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/container/cli.py", line 360, in conductor_commandline
    **params)
  File "/usr/local/lib/python2.7/dist-packages/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/container/core.py", line 610, in conductorcmd_build
    engine = load_engine(['BUILD'], engine_name, project_name, services, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/container/utils/loader.py", line 16, in load_engine
    package='container')
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/container/docker/engine.py", line 44, in <module>
    container.__version__
ImportError: You must install Ansible Container with Docker(tm) support. Try:
pip install ansible-container==0.9.1[docker]
Conductor terminated. Cleaning up.      command_rc=1 conductor_id=d59644d417905339358d0bd88e06fe214820c6ceb74baa15fb060baa8022e245 save_container=False
ERROR   Conductor exited with status 1
```

An inspection of `docker ps` shows a conductor image being created and apparently provisioned. A resulting conductor docker image also seems to be created.

 ```
$ docker images 
REPOSITORY           TAG                 IMAGE ID            CREATED             SIZE
foo-conductor            latest               c0f7cd696095      19 seconds ago      770MB
```

The steps to build from source should have ensured everything was in place (The issues mentioned in https://github.com/ansible/ansible-container/issues/692 may be related/significant).

This was how I built `ansible-container`
```
~/ansible-container$ sudo -H pip uninstall ansible-container
...
~/ansible-container$ sudo -H pip install --upgrade --force-reinstall .[docker]
```

##### EXPECTED RESULTS

Usual course of things. A build to start.

##### ACTUAL RESULTS

```

```

**Comment by chouseknecht** [comment]
@shalomb 

Thank you for using Ansible Container!  We appreciate you taking the time to share your feedback. 

I'll attempt to reproduce and sort this out.

**Comment by shalomb** [comment]
Moving comment to the right ticket.

@chouseknecht - turns out I had this in my `ansible-requirements.txt` 

```
$ cat ansible-requirements.txt 
setuptools>=36.2.7
pip>=9.0.1
ansible==2.3.2.0
ansible-container==0.9.1
docker>=2.4.2
docker-py>=1.9.0
```

Without this file in-place - I don't get the error. I've re-read upon the documentation of this file and I'm in error (I think I need a plain `requirements.txt`) - and it all makes sense now. For some reason, I missed the prologue at the top of the file that is generated by `ansible-container init` mentioning these were requirements for the `Ansible Container builder`.

I guess we could close this bug. I'm not sure what to suggest that would help someone like me further down the line - perhaps something in the documentation?

**Comment by chouseknecht** [comment]
Ah. So if you run the `init` command to start your project, it does state at the top of `ansible-requirements.txt` that the intention is modules related to the Conductor container.

Closing.
