### ISSUE TITLE
The roadmap under develop/ is significantly out of date

### ISSUE THREAD

**Issue by tima** [ansible/ansible-container#701]
##### ISSUE TYPE

 - Documentation Report

##### SUMMARY

Currently develop/ROADMAP.rst talks about v0.3 as the next release currently under development and need to be updated to reflect the v1.0 efforts.

##### STEPS TO REPRODUCE

See https://github.com/ansible/ansible-container/blob/develop/ROADMAP.rst

**Comment by chouseknecht** [comment]
I just updated it in PR #699. Generating doc site now.

**Comment by chouseknecht** [comment]
Assuming we can close now that roadmaps are up to date. We can continue to modify the roadmaps directly, as needed.
