### ISSUE TITLE
Add docker-compose as a dependency

### ISSUE THREAD

**Issue by alexppg** [ansible/ansible-container#707]
##### ISSUE TYPE

 - Feature Idea

##### SUMMARY

Since `ansible-container run` needs `docker-compose`, it makes sense add it as a requirement to requirements.txt.

##### EXPECTED RESULTS

It shouldn't ask for docker-compose.

##### ACTUAL RESULTS

It does ask for it.

**Comment by TomasTomecek** [comment]
Current version of ansible-container is not using docker-compose anymore:
```
$ git grep "compose" | grep import | wc -l
0
```

Please, update :)

**Comment by alexppg** [comment]
It actually returns something.
```
test/unit/container/docker/test_utils.py:from container.docker.utils import which_docker, config_to_compose
```
But aniway, ```ansible-container``` demanded it a while ago, but I'm not able to reproduce now, so sorry for make you waste your time x)
