### ISSUE TITLE
How to run multiple instances of the same service/container?

### ISSUE THREAD

**Issue by ksmets** [ansible/ansible-container#77]
Hi,

I'd like to know whether (and how) it's possible to build a service and run multiple instances of this service? This probably relates to being able to group the services together as with regular inventory groups and provide functionality like `docker-compose scale=...`

Any ideas?

thx, Koen

**Comment by darkn3rd** [comment]
Can we use defaults and bars that can inherit environment variables from the script?

**Comment by chouseknecht** [comment]
I don't think scaling services is something we need to add to ansible-container. It's certainly not a priority at this point. If you really want to scale a service, you can do it with `docker-compose scale=`, as you mention.
