### ISSUE TITLE
ModuleNotFoundError: No module named docker.models

### ISSUE THREAD

**Issue by davidnorthetal** [ansible/ansible-container#775]
- Bug Report

##### container.yml 

it's from one of your examples
```
version: "1"
services:
  web:
    image: centos:7
    ports:
      - "8080:80"

    command: ['/usr/bin/dumb-init', 'nginx', '-c', '/etc/nginx/nginx.conf', "-g", "daemon off;"]


registries: {}
```

##### OS / ENVIRONMENT

```
Ansible Container, version 0.9.2
Linux, fishbowl, 4.13.3-1-ARCH, #1 SMP PREEMPT Thu Sep 21 20:33:16 CEST 2017, x86_64
3.6.2 (default, Jul 20 2017, 03:52:27)
[GCC 7.1.1 20170630] /usr/bin/python
```
##### SUMMARY

ansible-container build and most other commands abort with a stacktrace

I ran the pip command it gives me back at the bottom, that doesn't change anything tho

##### STEPS TO REPRODUCE

build any ansible-container project

##### EXPECTED RESULTS

Don't throw a stacktrace

##### ACTUAL RESULTS

It threw a stacktrace:

```
ERROR   Unknown exception You must install Ansible Container with Docker(tm) support. Try:
pip install ansible-container[docker]==0.9.2
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/container/docker/engine.py", line 45, in <module>
    from docker.models.containers import RUN_HOST_CONFIG_KWARGS
ModuleNotFoundError: No module named 'docker.models'

During handling of the above exception, another exception occurred:
...
ImportError: You must install Ansible Container with Docker(tm) support. Try:
pip install ansible-container[docker]==0.9.2
```

**Comment by chouseknecht** [comment]
@davidnorthetal

It might be that you have an older version of the docker Python module installed. If you run `pip  list | grep docker`, you'll see what's actually installed. Try uninstalling what you find, and running `pip install --upgrade docker`.

If you take a glance at `setup.py`, you'll see under `extras_require`, for `docker`, it wants `docker>=2.4.0` to be installed.
