### ISSUE TITLE
roadmap for other containers support?

### ISSUE THREAD

**Issue by ghost** [ansible/ansible-container#782]
##### ISSUE TYPE
 - Feature Idea

##### container.yml 
```

```

##### OS / ENVIRONMENT
```

```
##### SUMMARY
Would be nice to get some sort of roadmap/todo to see if other container types are planned to be supported. If there's some sort of automation planned for dockerfile -> ansible-container migration than with the support for other container types it could be great migration tool to convert docker containers into other, more modern types.

##### STEPS TO REPRODUCE
```

```
##### EXPECTED RESULTS
Wiki or readme with roadmap links.

##### ACTUAL RESULTS
```

```

**Comment by TomasTomecek** [comment]
Could you please be more specific?

**Comment by chouseknecht** [comment]
@osmoc 

At the present time there are no plans to support other engines or container types, outside of the work being done by @TomasTomecek. See #760

There is already an `import` command available to convert Dockerfile -> an Ansible Container project. See [Migrating to Ansible Container](http://docs.ansible.com/ansible-container/migrating.html) on our docs site.

Our roadmap page has gotten a bit confusing. I'll see if I can fix that. We're trying to clean up a few loose ends and get 1.0 out the door.
