### ISSUE TITLE
Why does push need roles etc?

### ISSUE THREAD

**Issue by hans-d** [ansible/ansible-container#796]
##### ISSUE TYPE

 - Bug Report
 - Documentation Report

##### container.yml 

```
# whatever you want
```

##### OS / ENVIRONMENT

```
any
```
##### SUMMARY

When doing `ansible-container push` it wants to access the roles (and perhaps variables etc).
Unclear why that is needed -> documentation issue
It feels like push wants to do another build, and not "sends the latest build of your images" as is stated in the docs, or does some unneeded validations (build already passed)
The bug is related to push doing another build, it should just push the latest (already available) build.

##### STEPS TO REPRODUCE

```
make sure your roles are not in the default location, and you have build the image already using `build`
`ansible-container push --push-to myregistry:5000/testing`
```

##### EXPECTED RESULTS

pushing image to registr

##### ACTUAL RESULTS

Complaints about roles not being found

```
ansible.errors.AnsibleError: the role 'testrole' was not found in ./roles:/src/roles:/etc/ansible/roles:.
```

**Comment by chouseknecht** [comment]
I don't think it's attempting to do another build. What's likely happening is that the process of determining the `default` set of variable values, and thus resolve any variables that might be found in your `container.yml`, is attempting to access roles and read the `defaults/main.yml` files. 

A possible work around might be to use a different `container.yml` file by way of `--config-file` when performing a `push`, and not include any roles within service definitions. Not necessarily a great work around for your use case, but may do what you expect.

A potential fix for this use case is that during `push` we tell the config process to ignore any missing `defaults/main.yml`, and only report an error when we cannot resolve a variable within `container.yml`.

**Comment by hans-d** [comment]
I think it should only complain when the resolving of variables is interfering with the push itself. So most variables within container.yml could be unresolveable. In the end, only the service names need to be clear, as the content (roles, images, meta data like ports and volumes) should alreaby be in the image available.

**Comment by j00bar** [comment]
Definitely should address this one. I think the easiest thing to do is to flag which commands require full processing of service config and which don't. We can short circuit the config processing for the Conductor command for things like push that don't require full service configuration.

**Comment by j00bar** [comment]
@hans-d Thank you for the report - can you tell me if the above pull request fixes the issue for you? Thanks!

**Comment by hans-d** [comment]
@j00bar  not yet - need to test it :-)
