### ISSUE TITLE
Build performance

### ISSUE THREAD

**Issue by chouseknecht** [ansible/ansible-container#8]
I've been banging my way through creating an Ansible playbook that will build an image similar to Docker's Django demo: https://docs.docker.com/compose/django/. 

It's been an iterative, trial-and-error process, which is pretty typical when you're developing a playbook from scratch. Write a few tasks. Run. Debug errors. Run. Debug errors. Repeat. 

Each time I run *ansible-container build* I have to wait quite awhile before my playbook begins executing and building the container for my eventual image. From what I can see, it seems to be building a new Ansible container every time. 

Is there any way to make this faster? Does it really need to build the Ansible container each time? Seems like all it really needs is an updated copy of the ansible directory, which might be solved using a host volume. We could also start with a base image that includes Ansible already installed.

**Comment by cdrage** [comment]
I was wondering this too, takes quite a long time to initially build it >.>.

**Comment by cdrage** [comment]
Just a clip of the debug output, but it shows that it's pulling Python + rebuild the ansible container each-time. 
```sh
Rendered Jinja Template:                                                                                                                                                                                                                              [164/389]
FROM python:2.7

# Add the dockerproject repo
RUN apt-get update -y
RUN apt-get install -y apt-transport-https ca-certificates
RUN echo "deb https://apt.dockerproject.org/repo debian-jessie main">/etc/apt/sources.list.d/docker.list
RUN apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

# Install required packages, including docker-engine which gives us access a docker client
RUN apt-get update -y && \
    apt-get install -y python-setuptools git python-pip docker-engine && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ADD hosts  /etc/ansible/inventory/hosts
ADD ansible /ansible-tmp/
# RUN pip install -q --no-cache-dir 'ansible=='
RUN pip install -q --no-cache-dir -e git+https://github.com/ansible/ansible.git@devel#egg=ansible
RUN test '(! -f /ansible-tmp/requirements.txt)' || pip install --no-cache-dir -r /ansible-tmp/requirements.txt
RUN rm -rf /ansible-tmp/
Rendered Jinja Template:
[docker]
web ansible_host=ansible_web_1

Starting Docker build of Ansible Container image...
Cleaning up temporary directory /tmp/tmpT2tDNU...
{"stream":"Step 1 : FROM python:2.7\n"}

{"status":"Pulling from library/python","id":"2.7"}

{"status":"Digest: sha256:53ececa6c98c67079fc019644b364608f7fa4ae06cff372a5cb2fc82c90961d4"}

{"status":"Status: Image is up to date for python:2.7"}

{"stream":" ---\u003e a047e3d0ae2b\n"}
```
