### ISSUE TITLE
support running on local docker daemon (via docker socket)

### ISSUE THREAD

**Issue by dustymabe** [ansible/ansible-container#80]
Currently it is a requirement that a user have the Docker daemon listening via tcp or (recommended) via tls. For users running natively on linux and targeting the docker daemon on the local host there is no reason to use DOCKER_HOST or to expose their local docker daemon via tcp. It would be nice if we supported this as a use case.

I understand that ansible spins up a container that then communicates with the docker daemon from inside the container and that using DOCKER_HOST simplifies this design model. However, it is pretty simple to mount the docker socket into that container and achieve the same functionality.

**Comment by cdrage** [comment]
I agree with this. Would remove the need of having to use/setup DOCKER_HOST bash variables whenever using `ansible-container`, especially those whom are on Linux OS' / hosts.
