### ISSUE TITLE
release new version with fixing of #717

### ISSUE THREAD

**Issue by hans-d** [ansible/ansible-container#802]
##### ISSUE TYPE

 - Release requst

##### SUMMARY

With fixing of #717, there is not a new release yet. Can we have one?

**Comment by TomasTomecek** [comment]
On the other hand, this has an easy workaround: `mkdir -p ~/.docker/ && touch ~/.docker/config.json`

**Comment by chouseknecht** [comment]
New release for `1.0` is on the way. Don't have an exact date yet, but should be before the end of the year. In the meantime, you can [run from source](http://docs.ansible.com/ansible-container/installation.html#running-from-source), or do as @TomasTomecek suggests.
