### ISSUE TITLE
~/.docker/config.json is created as directory - push

### ISSUE THREAD

**Issue by hans-d** [ansible/ansible-container#803]
##### ISSUE TYPE

 - Bug Report

##### OS / ENVIRONMENT

```
nsible Container, version 0.9.3rc0
Linux, f886f17a7fb6, 4.9.49-moby, #1 SMP Wed Sep 27 23:17:17 UTC 2017, x86_64
2.7.12 (default, Nov 19 2016, 06:48:10)
[GCC 5.4.0 20160609] /usr/bin/python
```
##### SUMMARY

See also #717, use `push` instead of `build`. Also with an empty ~/.docker

##### EXPECTED RESULTS

Images can be pushed

##### ACTUAL RESULTS

```
  File "/_ansible/container/docker/engine.py", line 1160, in _get_registry_auth
    docker_config = json.load(open(config_path))
IOError: [Errno 21] Is a directory: u'/root/.docker/config.json'
```

**Comment by hans-d** [comment]
The error shows even if I do have a config.json file in the given location

**Comment by hans-d** [comment]
might be caused by the default conductor images still not being available with this version

**Comment by chouseknecht** [comment]
See #802
