### ISSUE TITLE
ansible-container can incorrectly assume names of container images

### ISSUE THREAD

**Issue by dustymabe** [ansible/ansible-container#81]
ansible-container assumes that the name of the image relating to a container to be brought up is `compose-<name>`. If you have a playbook that doesn't require a "build" for certain images then there will be no new committed image in the form of `compose-<name>` build on the machine. 

This means that running `ansible-container run` will error because of the bad assumption.

**Comment by j00bar** [comment]
Yep. Actively working on this guy. See: https://github.com/ansible/ansible-container/issues/68#issuecomment-227538016

**Comment by gregdek** [comment]
@j00bar should we close as dup of #68 then?

**Comment by dustymabe** [comment]
I think this does need to be fixed in order for #68 to be fixed, but I think it is fair to leave it as a separate issue. IMO the specific problem (for this piece of it) is more well defined here.

**Comment by j00bar** [comment]
They're separate but related. And both about to get pushed as fixes.
