### ISSUE TITLE
Can't find python

### ISSUE THREAD

**Issue by splisson-altair** [ansible/ansible-container#82]
When I run ansible-container build , the playbook starts to play but stop at setup stage:
ansible-container_1  | fatal: [reco]: FAILED! => {"changed": false, "failed": true, "module_stderr": "/bin/sh: 1: /usr/bin/python: not found\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}

Any suggestion?

**Comment by splisson-altair** [comment]
If I use python:2.7 as image in container.yml, I get sudo: notfound

**Comment by j00bar** [comment]
Can you possibly provide the complete output, your `DOCKER_*` environment variables, and your host OS information?

**Comment by splisson-altair** [comment]
camac06:ansible-repo splisson$ ansible-container -debug build
usage: ansible-container [-h] [--debug] [--engine ENGINE_NAME]
                         {run,help,shipit,init,build,push} ...
ansible-container: error: unrecognized arguments: -debug
camac06:ansible-repo splisson$ ansible-container --debug build
Project name is ansible-repo
Initialized with params: {'purge_last': True, 'subcommand': 'build', 'engine_args': {'engine_name': 'docker', 'purge_last': True, 'subcommand': 'build', 'engine_args': {...}, 'base_path': '/Users/splisson/projects/weyv/code/weyv-deployment/ansible-repo', 'ansible_options': u'', 'flatten': True, 'kwargs': {'debug': True, 'subcommand': 'build', 'no_purge_last': True}, 'debug': True, 'rebuild': False, 'no_purge_last': True}, 'no_purge_last': True, 'ansible_options': u'', 'flatten': True, 'kwargs': {'debug': True, 'subcommand': 'build', 'no_purge_last': True}, 'debug': True, 'rebuild': False}
(Re)building the Ansible Container image.
Using temporary directory /var/folders/v7/xxfxdgbj3qx98fnxbx7vl3mr000h97/T/tmp9NkdS7...
Building Docker Engine context...
Rendered Jinja Template:
FROM python:2.7

# Add the dockerproject repo
RUN apt-get update -y && \
    apt-get install -y apt-transport-https ca-certificates && \
    echo "deb https://apt.dockerproject.org/repo debian-jessie main">/etc/apt/sources.list.d/docker.list && \
    apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D && \
    apt-get update -y && \
    apt-get install -y python-setuptools git python-pip docker-engine && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ADD hosts  /etc/ansible/inventory/hosts
ADD ansible /ansible-tmp/
# RUN pip install -q --no-cache-dir 'ansible=='
RUN pip install -q --no-cache-dir -e git+https://github.com/ansible/ansible.git@devel#egg=ansible
RUN test '(! -f /ansible-tmp/requirements.txt)' || pip install --no-cache-dir -r /ansible-tmp/requirements.txt
RUN rm -rf /ansible-tmp/
Rendered Jinja Template:
[docker]
reco ansible_host=ansible_reco_1

Starting Docker build of Ansible Container image (please be patient)...
Cleaning up temporary directory /var/folders/v7/xxfxdgbj3qx98fnxbx7vl3mr000h97/T/tmp9NkdS7...
{"stream":"Step 1 : FROM python:2.7\n"}

{"stream":" ---\u003e a047e3d0ae2b\n"}

{"stream":"Step 2 : RUN apt-get update -y \u0026\u0026     apt-get install -y apt-transport-https ca-certificates \u0026\u0026     echo \"deb https://apt.dockerproject.org/repo debian-jessie main\"\u003e/etc/apt/sources.list.d/docker.list \u0026\u0026     apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D \u0026\u0026     apt-get update -y \u0026\u0026     apt-get install -y python-setuptools git python-pip docker-engine \u0026\u0026     apt-get clean \u0026\u0026 rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*\n"}

{"stream":" ---\u003e Using cache\n"}

{"stream":" ---\u003e 09191d189c60\n"}

{"stream":"Step 3 : ADD hosts /etc/ansible/inventory/hosts\n"}

{"stream":" ---\u003e Using cache\n"}

{"stream":" ---\u003e eb7d1eb1c66d\n"}

{"stream":"Step 4 : ADD ansible /ansible-tmp/\n"}

{"stream":" ---\u003e Using cache\n"}

{"stream":" ---\u003e 585e45d698fa\n"}

{"stream":"Step 5 : RUN pip install -q --no-cache-dir -e git+https://github.com/ansible/ansible.git@devel#egg=ansible\n"}

{"stream":" ---\u003e Using cache\n"}

{"stream":" ---\u003e 541f0cdada48\n"}

{"stream":"Step 6 : RUN test '(! -f /ansible-tmp/requirements.txt)' || pip install --no-cache-dir -r /ansible-tmp/requirements.txt\n"}

{"stream":" ---\u003e Using cache\n"}

{"stream":" ---\u003e 6d48981cbf98\n"}

{"stream":"Step 7 : RUN rm -rf /ansible-tmp/\n"}

{"stream":" ---\u003e Using cache\n"}

{"stream":" ---\u003e 871df6816146\n"}

{"stream":"Successfully built 871df6816146\n"}

Ansible Container image has ID sha256:871df681614642af2a821cf9f7cb717a3a8475e3c3231b1d8da921184848df70
Using temporary directory /var/folders/v7/xxfxdgbj3qx98fnxbx7vl3mr000h97/T/tmpWvQrjj...
Starting Docker Compose engine to build your images...
Using temporary directory /var/folders/v7/xxfxdgbj3qx98fnxbx7vl3mr000h97/T/tmpWUPLnv...
Compose derived from config:
{'reco': {'image': 'ubuntu:trusty', 'command': ['service', 'jetty', 'start'], 'ports': ['8080:80']}}
{'reco': {'image': 'ubuntu:trusty', 'command': 'sh -c "while true; do sleep 1; done"', 'ports': ['8080:80']}}
Config YAML is
reco:
  command: sh -c "while true; do sleep 1; done"
  image: ubuntu:trusty
  ports: ['8080:80']

Rendered Jinja Template:
ansible-container:
  image: "sha256:871df681614642af2a821cf9f7cb717a3a8475e3c3231b1d8da921184848df70"
  command: ansible-playbook -i /etc/ansible/inventory/hosts -c docker  --list-hosts main.yml
  environment:
    - DOCKER_HOST
    
    
    - COMPOSE_HTTP_TIMEOUT=3000
    - DOCKER_API_VERSION=1.24
  volumes:
    
    - /Users/splisson/projects/weyv/code/weyv-deployment/ansible-repo:/ansible-container/
  working_dir: /ansible-container/ansible/
  stdin_open: true
  tty: true
reco:
  command: sh -c "while true; do sleep 1; done"
  image: ubuntu:trusty
  ports: ['8080:80']

Attaching to ansible_ansible-container_1
Cleaning up Ansible Container builder...
Cleaning up temporary directory /var/folders/v7/xxfxdgbj3qx98fnxbx7vl3mr000h97/T/tmpWUPLnv...
Compose derived from config:
{'reco': {'image': 'ubuntu:trusty', 'command': 'sh -c "while true; do sleep 1; done"', 'ports': ['8080:80']}}
{'reco': {'working_dir': '/', 'command': 'sh -c "while true; do sleep 1; done"', 'user': 'root', 'image': 'ansible-repo-reco:latest', 'ports': ['8080:80']}}
Config YAML is
reco:
  command: sh -c "while true; do sleep 1; done"
  image: ansible-repo-reco:latest
  ports: ['8080:80']
  user: root
  working_dir: /

Rendered Jinja Template:
ansible-container:
  image: "sha256:871df681614642af2a821cf9f7cb717a3a8475e3c3231b1d8da921184848df70"
  command: "ansible-playbook -vvv -i /etc/ansible/inventory/hosts -c docker  main.yml"
  environment:
    - DOCKER_HOST
    
    
    - COMPOSE_HTTP_TIMEOUT=3000
    - DOCKER_API_VERSION=1.24
  volumes:
    
    - /Users/splisson/projects/weyv/code/weyv-deployment/ansible-repo:/ansible-container/
    - /var/run/docker.sock:/var/run/docker.sock
  working_dir: /ansible-container/ansible/
reco:
  command: sh -c "while true; do sleep 1; done"
  image: ansible-repo-reco:latest
  ports: ['8080:80']
  user: root
  working_dir: /

Attaching to ansible_reco_1, ansible_ansible-container_1
ansible-container_1  | Using /ansible-container/ansible/ansible.cfg as config file
ansible-container_1  | 
ansible-container_1  | PLAYBOOK: main.yml *************************************************************
ansible-container_1  | 1 plays in main.yml
ansible-container_1  | 
ansible-container_1  | PLAY [Configure reco on docker for api-dev] ************************************
ansible-container_1  | 
ansible-container_1  | TASK [setup] *******************************************************************
ansible-container_1  | Using module file /src/ansible/lib/ansible/modules/core/system/setup.py
ansible-container_1  | <ansible_reco_1> ESTABLISH DOCKER CONNECTION FOR USER: root
ansible-container_1  | <ansible_reco_1> EXEC ['/usr/bin/docker', 'exec', '-i', u'ansible_reco_1', u'/bin/sh', '-c', u'/bin/sh -c \'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1466639136.93-175943673892049 `" && echo ansible-tmp-1466639136.93-175943673892049="` echo $HOME/.ansible/tmp/ansible-tmp-1466639136.93-175943673892049 `" ) && sleep 0\'']
ansible-container_1  | <ansible_reco_1> PUT /tmp/tmpUwackO TO /root/.ansible/tmp/ansible-tmp-1466639136.93-175943673892049/setup.py
ansible-container_1  | <ansible_reco_1> EXEC ['/usr/bin/docker', 'exec', '-i', u'ansible_reco_1', u'/bin/sh', '-c', u"/bin/sh -c 'chmod -R u+x /root/.ansible/tmp/ansible-tmp-1466639136.93-175943673892049/ && sleep 0'"]
ansible-container_1  | <ansible_reco_1> EXEC ['/usr/bin/docker', 'exec', '-i', u'ansible_reco_1', u'/bin/sh', '-c', u'/bin/sh -c \'/usr/bin/python /root/.ansible/tmp/ansible-tmp-1466639136.93-175943673892049/setup.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1466639136.93-175943673892049/" > /dev/null 2>&1 && sleep 0\'']
ansible-container_1  | fatal: [reco]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "setup"}, "module_stderr": "/bin/sh: 1: /usr/bin/python: not found\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}
ansible-container_1  |  [WARNING]: Could not create retry file 'main.retry'.         Unable to create
ansible-container_1  | local directories(): [Errno 2] No such file or directory: ''
ansible-container_1  | 
ansible-container_1  | NO MORE HOSTS LEFT *************************************************************
ansible-container_1  | 
ansible-container_1  | PLAY RECAP *********************************************************************
ansible-container_1  | reco                       : ok=0    changed=0    unreachable=0    failed=1   
ansible-container_1  | 
ansible_ansible-container_1 exited with code 1
Aborting on container exit...
Stopping ansible_reco_1 ... done
EE Ansible playbook run failed.
Cleaning up Ansible Container builder...
Cleaning up temporary directory /var/folders/v7/xxfxdgbj3qx98fnxbx7vl3mr000h97/T/tmpWvQrjj...

**Comment by splisson-altair** [comment]
no DOCKER_* env variables

**Comment by splisson-altair** [comment]
I added:
- hosts: all
  gather_facts: false
  tasks:
    - raw: which python || apt-get update
    - raw: (which python && which aptitude) || apt-get install -y python python-apt aptitude

at the beginning of main.yml and now the run continues normally

**Comment by j00bar** [comment]
Ah, yes. For Debian derivatives, the apt module requires python and apt-python on the target host. Your solution is the way it should be done.

Do be careful though if you're using any prebaked images. Saying `hosts: all` will generate images for those hosts because the playbook touches them.

**Comment by AlesDokshanin** [comment]
Still getting the same error on **ubuntu:trusty** image with following **main.yml**
```
---
  - hosts: all
    become_user: root
    become_method: sudo

    pre_tasks:
    - raw: apt-get update
    - raw: apt-get install -y python python-apt aptitude

    roles:
    - { role: base-setup }
```

**Comment by toxickore** [comment]
thanks for the solution, it worked just fine for me
