### ISSUE TITLE
Be able to run tests locally

### ISSUE THREAD

**Issue by cdrage** [ansible/ansible-container#84]
Seems that `spellcheck` isn't on all OS'.

Can't seem to run this locally without modifying the scripts @mattclay ?

**Comment by cdrage** [comment]
Update: I'm going to add it to #85 for a method to run tests locally

**Comment by mattclay** [comment]
I believe you meant ```shellcheck```. It's widely available, but will need to be installed:

https://github.com/koalaman/shellcheck#installing

**Comment by cdrage** [comment]
@mattclay 
not anymore on debian: https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=spellcheck

```
▶ sudo apt-get install spellcheck
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package spellcheck
```

**Comment by cdrage** [comment]
See: https://github.com/koalaman/shellcheck/issues/439

Could you use an alternative package?

**Comment by mattclay** [comment]
@cdrage: Typo in your command, it should be s**h**ellcheck, not s**p**ellcheck.

**Comment by cdrage** [comment]
@mattclay I'm an idiot. :) thanks!
