### ISSUE TITLE
Source builds are failing on Python 2.7 and 3.6 as of Dec 19

### ISSUE THREAD

**Issue by geerlingguy** [ansible/ansible-container#840]
##### ISSUE TYPE

 - Bug Report

##### container.yml 

See: https://github.com/geerlingguy/solr-container/blob/master/container.yml

##### OS / ENVIRONMENT

  - Travis CI, Ubuntu 14.04.

##### SUMMARY

Starting today, all the source-based CI builds of my Solr Ansible Container project have been failing. The builds using the pip version are fine, and prior to today, builds have completed successfully (both source-based and pip-based—see https://travis-ci.org/geerlingguy/solr-container/builds).

Error under Python 2.7:

```
File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/role/definition.py", line 188, in _load_role_path
    raise AnsibleError("the role '%s' was not found in %s" % (role_name, ":".join(role_search_paths)), obj=self._ds)
ansible.errors.AnsibleError: the role 'setup' was not found in ./roles:/src/roles:/etc/ansible/roles:.
Conductor terminated. Cleaning up.	command_rc=1 conductor_id=02305ebfabedab9934f3338a057f66e301c08c583fd37bbfc9d0a3c24281007f save_container=False
ERROR	Conductor exited with status 1	
```

See failed build: https://travis-ci.org/geerlingguy/solr-container/jobs/318851273

Error under Python 3.6:

```
  File "/home/travis/build/geerlingguy/solr-container/ansible-container/container/core.py", line 41, in <module>
    from .config import DEFAULT_CONDUCTOR_BASE
  File "/home/travis/build/geerlingguy/solr-container/ansible-container/container/config.py", line 326
    except jsonschema.ValidationError, e:
                                     ^
SyntaxError: invalid syntax
```

See failed build: https://travis-ci.org/geerlingguy/solr-container/jobs/318851276

##### STEPS TO REPRODUCE

  1. Clone https://github.com/geerlingguy/solr-container locally
  2. Ensure you're using the source (latest master) version of ansible-container
  3. Run `ansible-container --var-file vars-7.x.yml build --no-container-cache`

(This also breaks on any of my other configs, for Solr 6, 5, 4, and 3.)

##### EXPECTED RESULTS

Build completes successfully.

##### ACTUAL RESULTS

Build is sad, and red. (See exact errors in Summary above).

**Comment by j00bar** [comment]
The 3.6 is totally my bad. Thank you - easy fix - and I need to update our test suite to run 2.7 and 3.6 so I don't idiot my way into those issues...

The other, I'll have to dig into. It'll be first on my agenda tomorrow. Thanks, as always, Jeff!

**Comment by j00bar** [comment]
Hey Jeff!

I've opened #842 which definitely fixes the PY3 issue, and it makes the code a little robust for the other issue. Please make sure you're pulling the latest Conductor base when running your test - the changes introduced in 0ac81c8 definitely would require new base images.

Thanks!

**Comment by geerlingguy** [comment]
@j00bar - For the Travis CI builds, I have no caches, so each build is in a clean environment. I kicked off a new build today for all the different tests, and both 3.6 and 2.7 are failing still :(

https://travis-ci.org/geerlingguy/solr-container/builds/325889313

Is there something additional I'd need to do when installing/setting up Ansible Container from source to tell it to grab a different version of the Conductor image? (I'm wondering if the source install is grabbing the latest _stable_/released conductor instead of the actual latest, maybe?)

**Comment by j00bar** [comment]
Sorry - finally getting back to this after the holiday. Can you kick off another CI build please?

**Comment by geerlingguy** [comment]
Kicked off a new build: https://travis-ci.org/geerlingguy/solr-container/builds/333005190

**Comment by geerlingguy** [comment]
All good now! Thanks for the fixes.
