### ISSUE TITLE
Default bridge clashes with LAN server IP

### ISSUE THREAD

**Issue by martvaha** [ansible/ansible-container#845]
- Bug Report

##### SUMMARY
Ansible-container creates a default bridge on `ansible-container run` and its subnet clashes with a LAN server IP address, making it impossible to access the server from the container. Docker itself has an easy way to change the default subnet in daemon.json by adding a bip with a suitable subnet.

##### EXPECTED RESULTS
There should be a way to chose the subnet for the automatically created network.

**Comment by j00bar** [comment]
Ansible Container uses the Docker daemon you provide. You're responsible for configuring it - and however you do so, Ansible Container should work fine with. Please let me know if it doesn't. Thanks!

**Comment by martvaha** [comment]
@j00bar I ended up using docker-compose/stack to run the containers because I couldn't figure out how to specify networks in container.yml. It seems to be unsupported at the moment or is there a way?
