### ISSUE TITLE
Differences between Docker and Ansible-Container

### ISSUE THREAD

**Issue by Manigunner** [ansible/ansible-container#859]
Hello,

Could anyone help me with the differences of using docker and ansible-container ?

**Comment by TomasTomecek** [comment]
We have an excellent documentation, so please go ahead and take your time reading it: http://docs.ansible.com/ansible-container/getting_started.html

For specific questions, we're here to answer. Unfortunately the question you asked is so generic, that answering it would take hundreds of lines.

**Comment by j00bar** [comment]
I agree with Tomas, however at the highest of high levels, Ansible Container is a project to leverage existing container engines like Docker to provide a workflow around Ansible content to build/run/deploy your containers in a container engine agnostic way. HTH - let us know if there's a more specific question we can answer.
