### ISSUE TITLE
0.9.3 release status

### ISSUE THREAD

**Issue by lcwill** [ansible/ansible-container#871]
##### ISSUE TYPE
 - Release request

##### SUMMARY
There are quite a number of bug fixes and updates that have accumulated since 0.9.2. Will there be an official `0.9.3` release?

Any updates on the timeline for `1.0`, since the most recent comment in #802?

**Comment by TomasTomecek** [comment]
As far as I know, the plan is to cut `0.9.3` soon.

**Comment by j00bar** [comment]
Indeed. The next time I have an opportunity to do bug pruning, the result will be 0.9.3.
