### ISSUE TITLE
Integrate ansible-container into a regular ansible workflow

### ISSUE THREAD

**Issue by etnbrd** [ansible/ansible-container#875]
##### ISSUE TYPE
 - Documentation Report (Question)

This question follows the previous questions #619 and #795 

How could I integrate the build of images into a regular ansible workflow?

I read that `ansible-container` can replace a DockerFile, and integrate it within ansible, and I need precisely this feature.
I would like running a playbook to build images, and 'import/register/fetch' them to make them available locally for later use, the same way I run a playbook to make sure a package is installed.

As I understand the answer in issue #619, `ansible-container` generates playbook for the `run` and `deploy` commands. Is it possible to write the playbook corresponding to the `build` command?
Would it use `docker_image` ansible module, or is it something internal to `ansible-container`?

I am willing to implement a module if need be. But I lack the vision of bigger picture, to know where to start. (And ideally, I would prefer to use `buildah`, `acbuild` or any other build tool that don't rely on the docker daemon)

**Comment by TomasTomecek** [comment]
There are connection plugins for `docker`, `buildah`, not sure about `acbuild`. So you can easily write a playbook and execute it against a container using those connection plugins. It's on my todo list to write a blog post about this.

As for `ansible-container`, I'm not entirely sure how you can integrate it into your existing Ansible workflow. The simplest thing to do would be to just use `command` module -- `command: ansible-container build`. @j00bar and @chouseknecht will definitely provide much better answers.

**Comment by etnbrd** [comment]
Thanks for your reply :)

I noticed the connecting plugins, but wasn't sure it had the same
capabilities than ansible-container.
Specifically, I imagined that these plugins were designed to run playbook
inside running containers, and not images.
Whereas ansible-container could run playbook to build images,  like a
Dockerfile.
But as images are essentially snapshot of containers, it could actually be
the same things, right ?

**Comment by j00bar** [comment]
Hi @etnbrd -

The `build` command generates a series of playbooks that one-at-a-time apply the roles specified in your `container.yml` to a base image. The cache detection and layer commits are all done in Python, not Ansible markup. You're welcome to write a playbook that uses `command` or `shell` to invoke Ansible Container, but otherwise I'm not sure what workflow you envision. Closing for now - please reopen if I've misunderstood.

-jag

**Comment by TomasTomecek** [comment]
@etnbrd so I finally wrote the blog post about using ansible and buildah together: https://blog.tomecek.net/post/building-containers-with-buildah-and-ansible/ Now just finish that PR for Ansible Container `/sigh`.

**Comment by etnbrd** [comment]
Awesome, that was fast, thanks :)
