### ISSUE TITLE
:q

### ISSUE THREAD

**Issue by damien-blanchet** [ansible/ansible-container#876]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### container.yml 

```

```

##### OS / ENVIRONMENT

```

```
##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```

```

**Comment by TomasTomecek** [comment]
`:q!`

**Comment by j00bar** [comment]
This is why I use emacs.
