### ISSUE TITLE
In the case of macOS the installation method is different

### ISSUE THREAD

**Issue by VTRyo** [ansible/ansible-container#902]
### ISSUE TYPE

* Documentation Report

## Installation
"https://github.com/ansible/ansible-container#installing"

`pip install ansible-container[docker,openshift]`

 but on MacOS you can install only with `pip install ansible-container docker openshift`.

Is this knowledge correct?

By the way, when you run the installation on MacOS it looks like the following.

```
 %pip install ansible-container[docker,openshift]
zsh: no matches found: ansible-container[docker,openshift]
```

**Comment by attilanagy** [comment]
@VTRyo This issue is related to zsh itself as square brackets have a special meaning. If you use another shell (Bash for example) then the command above is working under macOS.

You can run the installation command in the following ways in zsh. 

1. With quotes...

```
pip install "ansible-container[docker,openshift]"
```
2. With noglob...

```
noglob pip install ansible-container[docker,openshift]
```
