### ISSUE TITLE
Ansible Container fails to install

### ISSUE THREAD

**Issue by rppf** [ansible/ansible-container#932]
##### ISSUE TYPE

 - Bug Report

##### OS / ENVIRONMENT

```
Ubuntu 16.04 (I'm running Ubuntu in a VirtualBox)
Python 3.5.2
Pip 10.0.1
Setuptools 39.2.0
```
##### SUMMARY
I am not able to install ansible-container pip package with the instructions provided in README

##### STEPS TO REPRODUCE
```
$ sudo pip install ansible-container[docker,openshift]
```

##### EXPECTED RESULTS
ansible-container should be installed

##### ACTUAL RESULTS
This is the screenshot of the error.
![](https://i.imgur.com/NMlJzD4.png)

**Comment by Chostakovitch** [comment]
It is the same issue than #919. Pip 10 is not supported yet, either downgrade pip or pull from git and patch the import.

**Comment by rppf** [comment]
I'm going to close this issue then and wait for the Pip 10 to be supported.
