### ISSUE TITLE
Project plan?

### ISSUE THREAD

**Issue by hrstoyanov** [ansible/ansible-container#94]
Awesome project, addressing a significant pain for ansible and docker users!
I really want to try it out, but the separate build process is a hurdle. Any plans to merge it into Ansible, so that non-Python developers can give it a try?

Thanks

**Comment by j00bar** [comment]
I'm glad you're excited about it! It's actually the same build process that Ansible uses, as Ansible is Python also. What can we do to make it easier for non-Python people? I can definitely say that it will not be part of the normal Ansible distribution in the foreseeable future - the release cycle for Ansible Core is far more conservative than a preview project like this one.

**Comment by hrstoyanov** [comment]
@j00bar 
I was looking for a way to use ansible container without the python toolchain and compiling python code...

I guess I can put up a bit longer with my Docker+Ansible+SSHD+Systemd homebrew crap a bit longer, until this gets easier to install ...

Thanks

**Comment by gregdek** [comment]
We'll look to put together a pip release for 0.1 soon. First we've got to get to 0.1. ;)
