### ISSUE TITLE
Feature request: build --no-export

### ISSUE THREAD

**Issue by infothrill** [ansible/ansible-container#96]
**Summary**: add a command line option to the build command (--no-export) which will make ansible-container NOT export/commit the newly created container.

**Reasoning**: ansible-container seems a very good candidate to automate not only the creation of container images, but actually also to automate the testing of ansible playbooks and roles. In the case of tests, one usually doesn't want to keep an image.

Any thoughts? Is this thinking correct?

**Comment by gregdek** [comment]
That sounds like a good use case, yes.

**Comment by chouseknecht** [comment]
I think we can close those. AC no longer *flattens* the image (export/import of the container) by default. If a *flattened* image is desired, then run `ansible-container build --flatten`.
