### ISSUE TITLE
Create Dockerfile from Ansible roles

### ISSUE THREAD

**Issue by hackermd** [ansible/ansible-container#970]
##### ISSUE TYPE

 - Feature Idea

##### SUMMARY

There are now tools for converting ("importing") a Dockerfile into Ansible roles. There may be use cases were one would like to do the reverse, i.e. convert ("export") a set of Ansible roles into a Dockerfile.

Is there any existing functionality that I may have overlooked? If not, is that something you are considering supporting in the future?

**Comment by Voronenko** [comment]
As ansible roles relay on a python logic, in most of scenarios no direct mapping exist to shell commands (usually executed in Dockerfile)
