### ISSUE TITLE
setup.py install - error: Could not find suitable distribution for Requirement.parse('functools32==3.2.3.post2')

### ISSUE THREAD

**Issue by x12Mike** [ansible/ansible-container#98]
So not sure if this is an error with ansible-container per-se, or something specific to functools, however after running setup, I see the below error.

```...
Installing ansible-container script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/ansible_container-0.1-py2.7.egg
Processing dependencies for ansible-container==0.1
Searching for functools32==3.2.3.post2
Reading https://pypi.python.org/simple/functools32/
No local packages or download links found for functools32==3.2.3.post2
error: Could not find suitable distribution for Requirement.parse('functools32==3.2.3.post2')
```
For reference, I also installed functools32 from pip:

```
$ pip search functools32
functools32               - Backport of the functools module from Python 3.2.3 for use on 2.7 and PyPy.
  INSTALLED: 3.2.3-2 (latest)
```

What's interesting is that the ansible-container gets installed:
```
$ dir /usr/local/bin/ansible-container
4.0K -rwxr-xr-x 1 root root 345 Jun 29 13:20 /usr/local/bin/ansible-container
```

However, it will throw an error when trying to run:
```
$ /usr/local/bin/ansible-container
Traceback (most recent call last):
  File "/usr/local/bin/ansible-container", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 446, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 459, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: functools32==3.2.3.post2
```

Is this just something where I can modify the setup to look for ``3.2.3-2`` instead of ``3.2.3.post2``?

**Comment by mdevlin1** [comment]
I had the same issue. I fixed it by changing the "functools==3.2.3.post2" to "functools==3.2.3-2" in /ansible-container/requirements.txt

**Comment by x12Mike** [comment]
@mdevlin1 - Thank you for that.  I made the modification you mentioned, and got further.

I had to also modify that file for configparser and docker-py.  Once those were done, the install ran through fine.

I figured I'd mention that in case other folks ran into this. :)

**Comment by j00bar** [comment]
Thanks! We'll check the `requirements.txt` to see if there's been drift we need to be aware of.

**Comment by gregdek** [comment]
Should be fixed in devel and in upcoming release. Thanks @x12Mike!

**Comment by Harshika-Pareek** [comment]
Hi ,

I am getting issue Could not find suitable distribution for Requirement.parse while installing Paramiko Lib to windows . Could anyone help me out with this?

**Comment by ijas-aslam-mc** [comment]
i got some issues

Ijass-Air:tensorflow ijasmc0$ dir /usr/local/bin/ansible-container
-bash: dir: command not found
